// TwitchAchievementTrackerFrontend/src/components/ConfigXBL_02_XUID/ConfigXBL_02_XUID.tsx
import * as React from 'react'
import * as Base from '../../common/ConfigStepBase';
import { PlayerInfoCard } from '../../common/EBSTypes';
import { ConfigurationService } from '../../services/EBSConfigurationService';
import GamerCardComponent from '../GamerCard/GamerCard';
import ConfigXBL_03_TitleId from '../ConfigXBL_03_TitleId/ConfigXBL_03_TitleId';

interface ConfigXBL_02_XUIDProps extends Base.ConfigStepBaseProps {
    xApiKey: string,
}

type ConfigXBL_02_XUIDState = {
    xuidSearch: string;
    xuid: string;
    gamerCard: PlayerInfoCard;
    isLoading: boolean,
    isConfirmed: boolean,
}

export default class ConfigXBL_02_XUID extends Base.ConfigStepBase<ConfigXBL_02_XUIDProps, ConfigXBL_02_XUIDState> {
    state: ConfigXBL_02_XUIDState = {
        xuidSearch: "",
        xuid: null,
        gamerCard: null,
        isLoading: true,
        isConfirmed: false,
    }

    constructor(props: ConfigXBL_02_XUIDProps) {
        super(props);

        this.onChangeGamertagSearch = this.onChangeGamertagSearch.bind(this);
        this.onChangeGamertagSearch = this.onChangeGamertagSearch.bind(this);
        this.changeXuid = this.changeXuid.bind(this);
        this.onSearch = this.onSearch.bind(this);
    }

    componentDidMount = () => {
        let currentConfig = this.props.savedConfiguration;
        if (currentConfig?.xBoxLiveConfig?.streamerXuid){
            this.changeXuid(currentConfig.xBoxLiveConfig.streamerXuid);
        }
        else
        {
            this.setState({
                isLoading: false,
            });
        }
    }

    changeXuid = (xuid: string) => {
        this.setState({
            xuid: null,
            isLoading: true,
        });

        ConfigurationService.resolveXBoxLivePlayerInfo(xuid, this.props.xApiKey)
        .then(playerInfo => {
            this.setState({
                xuid: xuid,
                gamerCard: playerInfo,
                isLoading: false,
            });
        });
    }

    onChangeGamertagSearch = (e: React.ChangeEvent<HTMLInputElement>) => {
        this.setState({
            xuidSearch: e.currentTarget.value,
        })
    }

    onSearch = async (_e: React.SyntheticEvent<HTMLInputElement>) => {
        this.setState({
            xuidSearch: this.state.xuidSearch,
            xuid: null,
            gamerCard: null,
            isLoading: true,
        });

        let gamerCard = await ConfigurationService.resolveXBoxLiveGamertag(this.state.xuidSearch, this.props.xApiKey);

        this.setState({
            xuid: gamerCard.playerId,
            gamerCard: gamerCard,
            isLoading: false,
        });
    }

    onResetProfile = (_e: React.SyntheticEvent<HTMLInputElement>) => {
        this.setState({
            xuid: null,
            xuidSearch: '',
            gamerCard: null,
        });
    }

    onContinue = (_e: React.SyntheticEvent<HTMLInputElement>) => {
        this.setState({
            isConfirmed: true,
        });
    }

    unvalidate = (_e: any) => {
        this.setState({
            isConfirmed: false,
        })
    }

    render(){
        const isContinueEnabled = this.state.xuid;

        if (this.state.isConfirmed){
            return (
                <ConfigXBL_03_TitleId
                    savedConfiguration={this.props.savedConfiguration}
                    onValidate={this.props.onValidate}
                    onBack={this.unvalidate}
                    xApiKey={this.props.xApiKey}
                    streamerXuid={this.state.xuid} />
            )
        }

        let content: React.ReactNodeArray = null;
        if (this.state.isLoading)
        {
            content = [
                <div className="spinner"></div>
            ]
        }
        else if (this.state.gamerCard)
        {
            let changeButton = (<input type="button" value="Change" className="section" onClick={this.onResetProfile} />)
            content = [
                <GamerCardComponent playerInfo={this.state.gamerCard} buttonSection={changeButton} />,
                <input type="button" value="Back" onClick={this.onBack} />,
                <input type="button" value="Continue" disabled={!isContinueEnabled} onClick={this.onContinue} />
            ]
        }
        else
        {
            content = [
                <label htmlFor="xuidSearch">Streamer Id</label>,
                <input name="xuidSearch" type="text" placeholder="Search a Gamertag" value={this.state.xuidSearch} onChange={this.onChangeGamertagSearch} />,
                <input type="button" value="Search" onClick={this.onSearch} />,
                <input type="button" value="Back" onClick={this.onBack} />,
            ]
        }

        return [
           content,
        ]
    }
}

// TwitchAchievementTrackerFrontend/src/components/ConfigXBL_02_XUID/ConfigXBL_02_XUID.svelte
<script lang="ts">
import { ConfigurationService } from "../../services/EBSConfigurationService";
import type { ExtensionConfiguration, PlayerInfoCard } from "../../common/EBSTypes";
import GamerCard from "../GamerCard/GamerCard.svelte"
import ConfigXBL_03_TitleId from "../ConfigXBL_03_TitleId/ConfigXBL_03_TitleId.svelte"

export let onValidate: (e: any, configuration: ExtensionConfiguration) => void
export let onBack: (e: any) => void
export let savedConfiguration: ExtensionConfiguration
export let xApiKey: string

let xuidSearch: string = ""
let xuid: string = null
let gamerCard: PlayerInfoCard = null
let isLoading: boolean = true
let isConfirmed: boolean = false

function changeXuid(newXuid: string)
{
    xuid = null
    isLoading = true

    ConfigurationService.resolveXBoxLivePlayerInfo(newXuid, xApiKey)
        .then(playerInfo => {
            xuid = newXuid
            gamerCard = playerInfo
            isLoading = false
        });
}

function onChangeGamertagSearch(value: string)
{
    xuidSearch = value
}

async function onSearch(_e: any)
{
    xuidSearch = xuidSearch
    xuid = null
    gamerCard = null
    isLoading = true

    let resolvedGamerCard = await ConfigurationService.resolveXBoxLiveGamertag(this.state.xuidSearch, this.props.xApiKey);

    xuid = resolvedGamerCard.playerId
    gamerCard = resolvedGamerCard
    isLoading = false
}

function onResetProfile(_e: any)
{
    xuid = null
    xuidSearch = ''
    gamerCard = null
}

function onContinue(_e: any)
{
    isConfirmed = true
}

function unvalidate(_e: any)
{
    isConfirmed = false
}

$:{
    let currentConfig = savedConfiguration;
    if (currentConfig?.xBoxLiveConfig?.streamerXuid){
        changeXuid(currentConfig.xBoxLiveConfig.streamerXuid);
    }
    else
    {
        isLoading = false
    }
}

let isContinueEnabled: boolean
$: isContinueEnabled = xuid != null
</script>

{#if isConfirmed}
    <ConfigXBL_03_TitleId
        savedConfiguration={savedConfiguration}
        onValidate={onValidate}
        onBack={unvalidate}
        xApiKey={xApiKey}
        streamerXuid={xuid} />
{:else}
    {#if isLoading}
        <div class="spinner"></div>
    {:else if gamerCard != null }
        <GamerCard playerInfo={gamerCard}>
            <input slot="buttonSection" type="button" value="Change" class="section" on:click={onResetProfile} />
        </GamerCard>
        <input type="button" value="Back" on:click={onBack} />
        <input type="button" value="Continue" disabled={!isContinueEnabled} on:click={onContinue} />
    {:else}
        <label for="xuidSearch">Streamer Id</label>
        <input name="xuidSearch" type="text" placeholder="Search a Gamertag" value={xuidSearch} on:change={e => onChangeGamertagSearch(e.currentTarget.value)} />
        <input type="button" value="Search" on:click={onSearch} />
        <input type="button" value="Back" on:click={onBack} />
    {/if}
{/if}
