// TwitchAchievementTrackerFrontend/src/components/ConfigSteam_04_Locale/ConfigSteam_04_Locale.svelte
<script lang="ts">
import { ConfigurationService } from "../../services/EBSConfigurationService"
import type { ExtensionConfiguration, SupportedLanguage } from "../../common/EBSTypes"
import ConfigSteam_05_Confirm from "../ConfigSteam_05_Confirm/ConfigSteam_05_Confirm.svelte"

export let onValidate: (e: any, configuration: ExtensionConfiguration) => void
export let onBack: (e: any) => void
export let savedConfiguration: ExtensionConfiguration
export let webApiKey: string
export let steamProfileId: string
export let steamAppId: string

let isLoading: boolean =  true
let supportedLanguages: SupportedLanguage[] =  [ { langCode: '', displayName: "Loading..." } ]
let selectedLanguage: SupportedLanguage =  null
let isConfirmed: boolean =  false

function onSelect(value: string)
{
    selectedLanguage = supportedLanguages.find(l => l.langCode == value)
}

function onResetLanguage(_e: any)
{
    selectedLanguage = null
}

function onContinue(_e: any)
{
    isConfirmed = true
}

function unvalidate(_e: any)
{
    isConfirmed = false
}

let currentLanguage: string
$: currentLanguage = savedConfiguration?.steamConfig?.locale

ConfigurationService.getSteamSupportedLanguages(steamAppId, webApiKey)
    .then(languages => {
        isLoading = false
        supportedLanguages = [{ langCode: '', displayName: "Select language ..."}].concat(languages)
        selectedLanguage = currentLanguage ? languages.find(l => l.langCode == currentLanguage) : null
    });

let isContinueEnabled
$: isContinueEnabled = selectedLanguage != null;
</script>


{#if isConfirmed}
<ConfigSteam_05_Confirm
    savedConfiguration={savedConfiguration}
    onValidate={onValidate}
    onBack={unvalidate}
    webApiKey={webApiKey}
    steamProfileId={steamProfileId}
    steamAppId={steamAppId}
    locale={selectedLanguage.langCode} />
{:else}
    {#if isLoading}
        <div class="card">
            <div class="spinner"></div>
        </div>
    {:else if selectedLanguage != null}
        <div class="card">
            <h2>{selectedLanguage.displayName}</h2>
            <input type="button" class="section" name="LanguageChange" value="Change" onClick={onResetLanguage} />
        </div>
    {:else if supportedLanguages != null}
    <div class="card">
        <select name="language" class="selectLanguage" on:change={e => onSelect(e.currentTarget.value)}>
            {#each supportedLanguages as language}
                <option value={language.langCode}>{language.displayName}</option>
            {/each}
        </select>
    </div>
    {/if}
    <input type="button" value="Back" on:click={onBack} />
    <input type="button" disabled={!isContinueEnabled} value="Continue" on:click={onContinue} />
{/if}

// ReactTypescript/src/components/ConfigSteam_04_Locale/ConfigSteam_04_Locale.tsx
import * as React from 'react';
import * as Base from '../../common/ConfigStepBase'
import { SupportedLanguage, ActiveConfig } from '../../common/EBSTypes';
import { ConfigurationService } from '../../services/EBSConfigurationService';
import { ConfigurationState } from '../../services/ConfigurationStateService';


type ConfigSteam_04_LocaleState = {
    supportedLanguages: SupportedLanguage[],
    selectedLanguage: SupportedLanguage
}

export default class ConfigSteam_04_Locale extends Base.ConfigStepBase<any, any> {
    state: ConfigSteam_04_LocaleState = {
        supportedLanguages: [ { langCode: '', displayName: "Loading..." } ],
        selectedLanguage: null,
    };

    constructor(props: Base.ConfigStepBaseProps) {
        super(props);
        this.onContinue = this.onContinue.bind(this);
    }

    componentDidMount = () => {
        ConfigurationService.getSupportedLanguages(ActiveConfig.Steam, ConfigurationState.currentConfiguration.steamConfig.appId)
            .then(languages => {
                this.setState({
                    supportedLanguages: [{ langCode: '', displayName: "Select language ..."}].concat(languages),
                    selectedLanguage: null,
                });
            });
    }

    onSelect = (e: React.ChangeEvent<HTMLSelectElement>) => {
        this.setState({
            supportedLanguages: this.state.supportedLanguages,
            selectedLanguage: this.state.supportedLanguages.find(l => l.langCode == e.currentTarget.value),
        })
    }

    onContinue = (e: React.SyntheticEvent<HTMLInputElement>) => {
        ConfigurationState.currentConfiguration.steamConfig.locale = this.state.selectedLanguage.langCode;
        this.props.onValid(this, this.props.nextState);
    }
    
    render(){
        const isContinueEnabled = this.state.selectedLanguage;
        let selection;
        if (this.state.selectedLanguage)
        {
            selection = (
                <div className="selectedLanguage">
                    {this.state.selectedLanguage.displayName}
                </div>
            )
        }
        else if (this.state.supportedLanguages)
        {
            selection = (
                <select name="language" className="selectLanguage" onChange={this.onSelect}>
                    {
                        this.state.supportedLanguages.map((language, i) => (
                            <option value={language.langCode}>{language.displayName}</option>
                        ))
                    }
                </select>
            )
        }

        return [
            selection,
            <input type="button" disabled={!isContinueEnabled} value="Continue" onClick={this.onContinue} />
        ]
    }
}
