// ReactTypescript/src/components/ConfigSteam_02_SteamID/ConfigSteam_02_SteamID.tsx
import * as React from 'react';
import * as Base from '../../common/ConfigStepBase'
import { ConfigurationService, ValidationError } from '../../services/EBSConfigurationService';
import { ConfigurationState } from '../../services/ConfigurationStateService';
import { ExtensionConfiguration, ActiveConfig, PlayerInfoCard } from '../../common/EBSTypes';
import * as ServerConfig from '../../common/ServerConfig'
import EBSAchievementsService from '../../services/EBSAchievementsService';

type ConfigSteam_03_SteamIDState = {
    isLoading: boolean;
    isProfileUrlFormatValid: boolean;
    isProfileValid: boolean;
    steamProfileUrl: string;
    steamProfileId: string;
    steamProfile: PlayerInfoCard;
    errors: ValidationError[],
}

export default class ConfigSteam_03_SteamID extends Base.ConfigStepBase<Base.ConfigStepBaseProps, ConfigSteam_03_SteamIDState> {
    formatRegexp: RegExp = /^https:\/\/steamcommunity\.com\/id\/([^/]+)\/?$/i;
    steamIdRegexp: RegExp = /^[0-9]+$/;

    state: ConfigSteam_03_SteamIDState = {
        isLoading: true,
        isProfileUrlFormatValid: false,
        isProfileValid: false,
        steamProfileUrl: null,
        steamProfileId: null,
        steamProfile: null,
        errors: [],
    }

    constructor(props: Base.ConfigStepBaseProps){
        super(props);
    }

    componentDidMount = () => {
        let steamId = ConfigurationState.currentConfiguration.steamConfig.steamId;
        if (steamId && this.steamIdRegexp.test(steamId)) {
            ConfigurationService.resolveSteamPlayerInfo(steamId, ConfigurationState.currentConfiguration.steamConfig.webApiKey)
                .then(playerInfo => {
                    this.setState({
                        isLoading: false,
                        isProfileUrlFormatValid: false,
                        isProfileValid: true,
                        steamProfileId: steamId,
                        steamProfile: playerInfo,
                    });
                });
        }
        else
        {
            this.setState({
                isLoading: false,
            });
        }
    }

    onChangeProfileUrl = (e: React.ChangeEvent<HTMLInputElement>) => {
        let formatCheck = this.formatRegexp.test(e.currentTarget.value);
        this.setState({
            isProfileUrlFormatValid: formatCheck,
            isProfileValid: false,
            steamProfileUrl: formatCheck ? e.currentTarget.value : null,
        });
    }

    onValidate = async (e: React.SyntheticEvent<HTMLInputElement>) => {
        let split = this.formatRegexp.exec(this.state.steamProfileUrl);
        let profileId = split[1];
        let resolvedProfile: PlayerInfoCard = null;

        if (! this.steamIdRegexp.test(profileId))
        {
            resolvedProfile = await ConfigurationService.resolveSteamVanityUrl(profileId, ConfigurationState.currentConfiguration.steamConfig.webApiKey);
            profileId = resolvedProfile.playerId;
        }
        else
        {
            resolvedProfile = await ConfigurationService.resolveSteamPlayerInfo(profileId, ConfigurationState.currentConfiguration.steamConfig.webApiKey);
        }
        
        const configuration: ExtensionConfiguration = {
            activeConfig: ActiveConfig.Steam,
            steamConfig: {
                steamId: profileId,
                webApiKey: ConfigurationState.currentConfiguration.steamConfig.webApiKey,
                appId: null,
                locale: null
            },
            version: ServerConfig.EBSVersion,
            xBoxLiveConfig: null
        }
        
        let errors = await ConfigurationService.validateConfiguration(configuration);
        errors = errors.filter(e => e.path == "SteamConfig.WebApiKey" || e.path == "SteamConfig.SteamId");

        this.setState({
            errors: errors,
        });

        if (this.state.errors.length == 0)
        {
            this.setState({
                isProfileValid: true,
                steamProfileId: profileId,
                steamProfile: resolvedProfile,
            });
        }
    }
    
    onResetProfile = (e: React.SyntheticEvent<HTMLInputElement>) => {
        this.setState({
            isProfileUrlFormatValid: false,
            isProfileValid: false,
            steamProfileId: null,           
            steamProfile: null,
        });
    }

    onContinue = (e: React.SyntheticEvent<HTMLInputElement>) => {
        ConfigurationState.currentConfiguration.steamConfig.steamId = this.state.steamProfileId;
        this.props.onValid(this, this.props.nextState);
    }

    render(){
        let isCheckEnabled = this.state.isProfileUrlFormatValid;
        let isContinueEnabled = this.state.isProfileValid;

        let playerInfoCard = null;
        if (! this.state.isLoading)
        {
            if (this.state.steamProfile)
            {
                playerInfoCard = [
                    <div className="card">
                        <h2 className="section">{this.state.steamProfile.playerName}</h2>
                        <div className="section">Id: {this.state.steamProfile.playerId}</div>
                        <img src={this.state.steamProfile.avatarUrl} className="section media" />
                        <input type="button" value="Change" className="section" onClick={this.onResetProfile} />
                    </div>
                ]
            }
            else
            {
                playerInfoCard = [
                    <label htmlFor="vanityUrl">Steam Profile URL</label>,
                    <input name="vanityUrl" type="text" pattern="https:\/\/steamcommunity\.com\/id\/([^/]+)\/?$" placeholder="Enter your Steam profile URL" onChange={this.onChangeProfileUrl} />,
                    <ul>
                        {this.state.errors.map((error, i) => (
                            <li key={error.path + '_' + i}>
                                {error.path}: {error.errorDescription}
                            </li>
                        ))}
                    </ul>,
                    <input type="button" value="Search" disabled={!isCheckEnabled} onClick={this.onValidate} />
                ]
            }
        }
        else
        {
            playerInfoCard = (
                <div>Loading ...</div>
            )
        }

        return [,
            playerInfoCard,
            <input type="button" value="Continue" disabled={!isContinueEnabled} onClick={this.onContinue} />
        ]
    }
}

// TwitchAchievementTrackerFrontend/src/components/ConfigSteam_02_SteamID/ConfigSteam_02_SteamID.svelte
<script lang="ts">
import { ActiveConfig, ExtensionConfiguration, PlayerInfoCard } from "../../common/EBSTypes"
import { ConfigurationService, ValidationError } from "../../services/EBSConfigurationService"
import { EBSVersion } from "../../common/ServerConfig"
import GamerCard from "../GamerCard/GamerCard.svelte"
import ValidationErrorList from "../ValidationErrorList/ValidationErrorList.svelte"
import ConfigSteam_03_AppId from "../ConfigSteam_03_AppId/ConfigSteam_03_AppId.svelte"
import type { SvelteComponent } from "svelte/internal";

export let onValidate: (e: any, configuration: ExtensionConfiguration) => void
export let onBack: (e: any) => void
export let savedConfiguration: ExtensionConfiguration
export let webApiKey:string = ""

const formatRegexp: RegExp = /^https:\/\/steamcommunity\.com\/(profiles|id)\/([^\/]+)(\/.*)?$/i
const steamIdRegexp: RegExp = /^[0-9]+$/

let isLoading: boolean = true
let isProfileUrlFormatValid: boolean = false
let isProfileValid: boolean = false
let isConfirmed: boolean = false
let unvalidatedUrl: string = null
let steamProfileUrl: string = null
let steamProfileId: string = null
let steamProfile: PlayerInfoCard = null
let errors: ValidationError[] = []


function onChangeProfileUrl(value: string)
{
    let formatCheck = formatRegexp.test(value);
    isProfileUrlFormatValid = formatCheck
    isProfileValid = false
    unvalidatedUrl = value
    steamProfileUrl = formatCheck ? value : null
}

async function doValidate(_e: any)
{
    if (isProfileValid)
    {
        isConfirmed = true
    }

    isLoading = true

    try {
        let split = formatRegexp.exec(steamProfileUrl);
        let profileId = split[2];
        let resolvedProfile: PlayerInfoCard = null;

        if (! steamIdRegexp.test(profileId))
        {
            resolvedProfile = await ConfigurationService.resolveSteamVanityUrl(profileId, webApiKey);
            profileId = resolvedProfile.playerId;
        }
        else
        {
            resolvedProfile = await ConfigurationService.resolveSteamPlayerInfo(profileId, webApiKey);
        }
        
        const configuration: ExtensionConfiguration = {
            activeConfig: ActiveConfig.Steam,
            steamConfig: {
                steamId: profileId,
                webApiKey: webApiKey,
                appId: null,
                locale: null
            },
            version: EBSVersion,
            xBoxLiveConfig: null
        }
        
        let newErrors = await ConfigurationService.validateConfiguration(configuration)
        errors = newErrors.filter(e => e.path == "SteamConfig.WebApiKey" || e.path == "SteamConfig.SteamId")

        if (errors.length == 0)
        {
            isProfileValid = true
            steamProfileId = profileId
            steamProfile = resolvedProfile
        }
    }
    finally
    {
        isLoading = false
    }
}

function onResetProfile(_e: any)
{
    isProfileUrlFormatValid = true
    isProfileValid = false
    steamProfileId = null           
    steamProfile = null
}

function unvalidate(_e: any)
{
    isConfirmed = false
}

let steamId:string
$:{
    steamId = savedConfiguration?.steamConfig?.steamId
    if (steamId && steamIdRegexp.test(steamId)) {
        ConfigurationService.resolveSteamPlayerInfo(steamId, webApiKey)
            .then(playerInfo => {
                isLoading = false
                isProfileUrlFormatValid = false
                isProfileValid = true
                steamProfileId = steamId
                steamProfile = playerInfo
            });
    }
    else
    {
        isLoading = false
    }
}

let isContinueEnabled:boolean
$: isContinueEnabled = isProfileUrlFormatValid || isProfileValid;

</script>


{#if isConfirmed}
<ConfigSteam_03_AppId
    savedConfiguration={savedConfiguration}
    onValidate={onValidate}
    onBack={unvalidate}
    webApiKey={webApiKey}
    steamProfileId={steamProfileId} />
{:else}
    {#if !isLoading}
        {#if steamProfile}
            <GamerCard playerInfo={steamProfile}>
                <input slot="buttonSection" type="button" value="Change" class="section" on:click={onResetProfile} />
            </GamerCard>
        {:else}
            <label for="vanityUrl">Steam Profile URL</label>
            <input name="vanityUrl" type="text"
                pattern="https:\/\/steamcommunity\.com\/(profiles|id)\/([^\/]+)(\/.*)?$"
                placeholder="Enter your Steam profile URL"
                value={unvalidatedUrl}
                on:input={e => onChangeProfileUrl(e.currentTarget.value)}
                on:change={e => onChangeProfileUrl(e.currentTarget.value)} />
            <div>
                <span class="icon-info"></span> You can copy your Profile URL by right-clicking on your profile page on the Steam application, and selecting 'Copy Page URL'.
            </div>
            <ValidationErrorList errors={errors} />
        {/if}
    {:else}
        <div class="card">
            <div class="spinner"></div>
        </div>
    {/if}
    <input type="button" value="Back" onClick={onBack} />
    <input type="button" value="Continue" disabled={!isContinueEnabled} on:click={doValidate} />
{/if}
