// TwitchAchievementTrackerFrontend/src/components/ConfigSteam_02_SteamID/ConfigSteam_02_SteamID.tsx
import * as React from 'react';
import * as Base from '../../common/ConfigStepBase'
import { ConfigurationService, ValidationError } from '../../services/EBSConfigurationService';
import { ExtensionConfiguration, ActiveConfig, PlayerInfoCard } from '../../common/EBSTypes';
import * as ServerConfig from '../../common/ServerConfig'
import GamerCardComponent from '../GamerCard/GamerCard';
import ConfigSteam_03_AppId from '../ConfigSteam_03_AppId/ConfigSteam_03_AppId'
import ValidationErrorList from '../ValidationErrorList/ValidationErrorList';

interface ConfigSteam_03_SteamIDProps extends Base.ConfigStepBaseProps {
    webApiKey: string;
}

type ConfigSteam_03_SteamIDState = {
    isLoading: boolean;
    isProfileUrlFormatValid: boolean;
    isProfileValid: boolean;
    isConfirmed: boolean;
    unvalidatedUrl: string;
    steamProfileUrl: string;
    steamProfileId: string;
    steamProfile: PlayerInfoCard;
    errors: ValidationError[],
}

export default class ConfigSteam_03_SteamID extends Base.ConfigStepBase<ConfigSteam_03_SteamIDProps, ConfigSteam_03_SteamIDState> {
    formatRegexp: RegExp = /^https:\/\/steamcommunity\.com\/(profiles|id)\/([^\/]+)(\/.*)?$/i;
    steamIdRegexp: RegExp = /^[0-9]+$/;

    state: ConfigSteam_03_SteamIDState = {
        isLoading: true,
        isProfileUrlFormatValid: false,
        isProfileValid: false,
        isConfirmed: false,
        unvalidatedUrl: null,
        steamProfileUrl: null,
        steamProfileId: null,
        steamProfile: null,
        errors: [],
    }

    constructor(props: ConfigSteam_03_SteamIDProps){
        super(props);

        this.onChangeProfileUrl = this.onChangeProfileUrl.bind(this);
        this.onValidate = this.onValidate.bind(this);
        this.onResetProfile = this.onResetProfile.bind(this);
        this.unvalidate = this.unvalidate.bind(this);
    }

    componentDidMount = () => {
        let steamId = this.props.savedConfiguration?.steamConfig?.steamId;
        if (steamId && this.steamIdRegexp.test(steamId)) {
            ConfigurationService.resolveSteamPlayerInfo(steamId, this.props.webApiKey)
                .then(playerInfo => {
                    this.setState({
                        isLoading: false,
                        isProfileUrlFormatValid: false,
                        isProfileValid: true,
                        steamProfileId: steamId,
                        steamProfile: playerInfo,
                    });
                });
        }
        else
        {
            this.setState({
                isLoading: false,
            });
        }
    }

    onChangeProfileUrl = (e: React.ChangeEvent<HTMLInputElement>) => {
        let formatCheck = this.formatRegexp.test(e.currentTarget.value);
        this.setState({
            isProfileUrlFormatValid: formatCheck,
            isProfileValid: false,
            unvalidatedUrl: e.currentTarget.value,
            steamProfileUrl: formatCheck ? e.currentTarget.value : null,
        });
    }

    onValidate = async (_e: React.SyntheticEvent<HTMLInputElement>) => {
        if (this.state.isProfileValid)
        {
            this.setState({
                isConfirmed: true,
            });
        }

        this.setState({
            isLoading: true,
        })

        try {
            let split = this.formatRegexp.exec(this.state.steamProfileUrl);
            let profileId = split[2];
            let resolvedProfile: PlayerInfoCard = null;
    
            if (! this.steamIdRegexp.test(profileId))
            {
                resolvedProfile = await ConfigurationService.resolveSteamVanityUrl(profileId, this.props.webApiKey);
                profileId = resolvedProfile.playerId;
            }
            else
            {
                resolvedProfile = await ConfigurationService.resolveSteamPlayerInfo(profileId, this.props.webApiKey);
            }
            
            const configuration: ExtensionConfiguration = {
                activeConfig: ActiveConfig.Steam,
                steamConfig: {
                    steamId: profileId,
                    webApiKey: this.props.webApiKey,
                    appId: null,
                    locale: null
                },
                version: ServerConfig.EBSVersion,
                xBoxLiveConfig: null
            }
            
            let errors = await ConfigurationService.validateConfiguration(configuration);
            errors = errors.filter(e => e.path == "SteamConfig.WebApiKey" || e.path == "SteamConfig.SteamId");
            
            this.setState({
                errors: errors,
            });
    
            if (this.state.errors.length == 0)
            {
                this.setState({
                    isProfileValid: true,
                    steamProfileId: profileId,
                    steamProfile: resolvedProfile,
                });
            }
        }
        finally
        {
            this.setState({
                isLoading: false,
            });
        }
    }
    
    onResetProfile = (_e: React.SyntheticEvent<HTMLInputElement>) => {
        this.setState({
            isProfileUrlFormatValid: true,
            isProfileValid: false,
            steamProfileId: null,           
            steamProfile: null,
        });
    }

    unvalidate = (_e: React.SyntheticEvent<HTMLElement>) => {
        this.setState({
            isConfirmed: false,
        });
    }

    render(){
        let isCheckEnabled = this.state.isProfileUrlFormatValid;
        let isContinueEnabled = isCheckEnabled || this.state.isProfileValid;

        if (this.state.isConfirmed){
            return (
                <ConfigSteam_03_AppId
                    savedConfiguration={this.props.savedConfiguration}
                    onValidate={this.props.onValidate}
                    onBack={this.unvalidate}
                    webApiKey={this.props.webApiKey}
                    steamProfileId={this.state.steamProfileId} />
            )
        }

        let playerInfoCard = null;
        if (! this.state.isLoading)
        {
            if (this.state.steamProfile)
            {
                let changeButton = (
                    <input type="button" value="Change" className="section" onClick={this.onResetProfile} />
                )
                playerInfoCard = [
                    <GamerCardComponent playerInfo={this.state.steamProfile} buttonSection={changeButton} />,
                ]
            }
            else
            {
                playerInfoCard = [
                    <label htmlFor="vanityUrl">Steam Profile URL</label>,
                    <input name="vanityUrl" type="text"
                        pattern="https:\/\/steamcommunity\.com\/(profiles|id)\/([^\/]+)(\/.*)?$"
                        placeholder="Enter your Steam profile URL"
                        value={this.state.unvalidatedUrl}
                        onChange={this.onChangeProfileUrl} />,
                    <div>
                        <span className="icon-info"></span> You can copy your Profile URL by right-clicking on your profile page on the Steam application, and selecting 'Copy Page URL'.
                    </div>,
                    <ValidationErrorList errors={this.state.errors} />
                ]
            }
        }
        else
        {
            playerInfoCard = (
                <div className="card">
                    <div className="spinner"></div>
                </div>
            )
        }

        return [
            playerInfoCard,
            <input type="button" value="Back" onClick={this.onBack} />,
            <input type="button" value="Continue" disabled={!isContinueEnabled} onClick={this.onValidate} />
        ]
    }
}

// TwitchAchievementTrackerFrontend/src/components/ConfigSteam_02_SteamID/ConfigSteam_02_SteamID.svelte
<script lang="ts">
import { ActiveConfig, ExtensionConfiguration, PlayerInfoCard } from "../../common/EBSTypes"
import { ConfigurationService, ValidationError } from "../../services/EBSConfigurationService"
import { EBSVersion } from "../../common/ServerConfig"
import GamerCard from "../GamerCard/GamerCard.svelte"
import ValidationErrorList from "../ValidationErrorList/ValidationErrorList.svelte"
import ConfigSteam_03_AppId from "../ConfigSteam_03_AppId/ConfigSteam_03_AppId.svelte"
import type { SvelteComponent } from "svelte/internal";

export let onValidate: (e: any, configuration: ExtensionConfiguration) => void
export let onBack: (e: any) => void
export let savedConfiguration: ExtensionConfiguration
export let webApiKey:string = ""

const formatRegexp: RegExp = /^https:\/\/steamcommunity\.com\/(profiles|id)\/([^\/]+)(\/.*)?$/i
const steamIdRegexp: RegExp = /^[0-9]+$/

let isLoading: boolean = true
let isProfileUrlFormatValid: boolean = false
let isProfileValid: boolean = false
let isConfirmed: boolean = false
let unvalidatedUrl: string = null
let steamProfileUrl: string = null
let steamProfileId: string = null
let steamProfile: PlayerInfoCard = null
let errors: ValidationError[] = []


function onChangeProfileUrl(value: string)
{
    let formatCheck = formatRegexp.test(value);
    isProfileUrlFormatValid = formatCheck
    isProfileValid = false
    unvalidatedUrl = value
    steamProfileUrl = formatCheck ? value : null
}

async function doValidate(_e: any)
{
    if (isProfileValid)
    {
        isConfirmed = true
    }

    isLoading = true

    try {
        let split = formatRegexp.exec(steamProfileUrl);
        let profileId = split[2];
        let resolvedProfile: PlayerInfoCard = null;

        if (! steamIdRegexp.test(profileId))
        {
            resolvedProfile = await ConfigurationService.resolveSteamVanityUrl(profileId, webApiKey);
            profileId = resolvedProfile.playerId;
        }
        else
        {
            resolvedProfile = await ConfigurationService.resolveSteamPlayerInfo(profileId, webApiKey);
        }
        
        const configuration: ExtensionConfiguration = {
            activeConfig: ActiveConfig.Steam,
            steamConfig: {
                steamId: profileId,
                webApiKey: webApiKey,
                appId: null,
                locale: null
            },
            version: EBSVersion,
            xBoxLiveConfig: null
        }
        
        let newErrors = await ConfigurationService.validateConfiguration(configuration)
        errors = newErrors.filter(e => e.path == "SteamConfig.WebApiKey" || e.path == "SteamConfig.SteamId")

        if (errors.length == 0)
        {
            isProfileValid = true
            steamProfileId = profileId
            steamProfile = resolvedProfile
        }
    }
    finally
    {
        isLoading = false
    }
}

function onResetProfile(_e: any)
{
    isProfileUrlFormatValid = true
    isProfileValid = false
    steamProfileId = null           
    steamProfile = null
}

function unvalidate(_e: any)
{
    isConfirmed = false
}

let steamId:string
$:{
    steamId = savedConfiguration?.steamConfig?.steamId
    if (steamId && steamIdRegexp.test(steamId)) {
        ConfigurationService.resolveSteamPlayerInfo(steamId, webApiKey)
            .then(playerInfo => {
                isLoading = false
                isProfileUrlFormatValid = false
                isProfileValid = true
                steamProfileId = steamId
                steamProfile = playerInfo
            });
    }
    else
    {
        isLoading = false
    }
}

let isContinueEnabled:boolean
$: isContinueEnabled = isProfileUrlFormatValid || isProfileValid;

</script>


{#if isConfirmed}
<ConfigSteam_03_AppId
    savedConfiguration={savedConfiguration}
    onValidate={onValidate}
    onBack={unvalidate}
    webApiKey={webApiKey}
    steamProfileId={steamProfileId} />
{:else}
    {#if !isLoading}
        {#if steamProfile}
            <GamerCard playerInfo={steamProfile}>
                <input slot="buttonSection" type="button" value="Change" class="section" on:click={onResetProfile} />
            </GamerCard>
        {:else}
            <label for="vanityUrl">Steam Profile URL</label>
            <input name="vanityUrl" type="text"
                pattern="https:\/\/steamcommunity\.com\/(profiles|id)\/([^\/]+)(\/.*)?$"
                placeholder="Enter your Steam profile URL"
                value={unvalidatedUrl}
                on:input={e => onChangeProfileUrl(e.currentTarget.value)}
                on:change={e => onChangeProfileUrl(e.currentTarget.value)} />
            <div>
                <span class="icon-info"></span> You can copy your Profile URL by right-clicking on your profile page on the Steam application, and selecting 'Copy Page URL'.
            </div>
            <ValidationErrorList errors={errors} />
        {/if}
    {:else}
        <div class="card">
            <div class="spinner"></div>
        </div>
    {/if}
    <input type="button" value="Back" onClick={onBack} />
    <input type="button" value="Continue" disabled={!isContinueEnabled} on:click={doValidate} />
{/if}
