// TwitchAchievementTrackerFrontend/src/components/ConfigSteam_01_WebAPIKey/ConfigSteam_01_WebAPIKey.svelte
<script lang="ts">
import { ConfigurationService, ValidationError } from "../../services/EBSConfigurationService";
import { ActiveConfig, ExtensionConfiguration, SteamConfiguration } from "../../common/EBSTypes";
import { EBSVersion } from "../../common/ServerConfig";
import SecretKeyInput from "../SecretKeyInput/SecretKeyInput.svelte";
import ValidationErrorList from "../ValidationErrorList/ValidationErrorList.svelte";
import ConfigSteam_02_SteamID from "../ConfigSteam_02_SteamID/ConfigSteam_02_SteamID.svelte"

export let onValidate: (e: any, configuration: ExtensionConfiguration) => void
export let onBack: (e: any) => void
export let savedConfiguration: ExtensionConfiguration

let isSyntaxValid: boolean = false
let isSyntaxError: boolean = false
let isValidating: boolean = false
let isKeyValid: boolean = false
let enteredApiKey: string = ""
let errors: ValidationError[] = []
let isContinueEnabled = false

const formatRegexp = /^[0-9a-f]+$/i
const formatFullMatchRegexp = (/^[0-9a-f]{32}$/i)

function changeWebApiValue(value: string)
{
    console.log(value)
    let formatCheck = formatFullMatchRegexp.test(value)
    let isValid = formatRegexp.test(value)

    isSyntaxValid = formatCheck
    isSyntaxError = !isValid
    enteredApiKey = value
}

async function onContinue(_e: any)
{
    isValidating = true

    const configuration: ExtensionConfiguration = {
        activeConfig: ActiveConfig.Steam,
        xBoxLiveConfig: null,
        version: EBSVersion,
        steamConfig: {
            webApiKey: enteredApiKey,
            locale: null,
            steamId: null,
            appId: null,
        }
    }

    let errors: ValidationError[] = [];
    try
    {
        errors = await ConfigurationService.validateConfiguration(configuration);
        errors = errors.filter(e => e.path == "SteamConfig.WebApiKey");
    }
    catch(e)
    {
        errors.push({
            errorCode: "EBSError",
            errorDescription: "Error validating WebApiKey",
            path: "",
        });
    }

    errors = errors
    isValidating = false
    isKeyValid = errors.length == 0

    if (errors.length == 0)
    {
    }
}

$:{
    let currentConfig: SteamConfiguration = savedConfiguration?.steamConfig;
    if (currentConfig?.webApiKey)
    {
        changeWebApiValue(currentConfig.webApiKey);
    }
}

$: isContinueEnabled = isSyntaxValid && !isValidating
</script>

{#if isKeyValid}
<ConfigSteam_02_SteamID
            savedConfiguration={savedConfiguration}
            onValidate={onValidate}
            onBack={_e => isKeyValid = false}
            webApiKey={enteredApiKey} />
{:else}
<label for="webApiKey">Steam WebApi Key</label>
<SecretKeyInput isSyntaxValid={isSyntaxValid} onChangeValue={e => changeWebApiValue(e.currentTarget.value)} keyValue={enteredApiKey} size={37} pattern="[0-9a-fA-F]{32}" placeholder="Enter your Steam WebAPI key" />
<div>
    <span class="icon-info"></span> You can apply for a WebAPI Key on <a href="https://steamcommunity.com/dev/apikey" target="_blank">https://steamcommunity.com/dev/apikey</a>.
</div>
<ValidationErrorList errors={errors} />
<input type="button" value="Cancel" on:click={onBack} />
<input type="button" value="Continue" disabled={!isContinueEnabled} on:click={onContinue} />
{/if}

// ReactTypescript/src/components/ConfigSteam_01_WebAPIKey/ConfigSteam_01_WebAPIKey.tsx
import * as React from 'react'
import '../../common/ConfigStepBase'
import * as Base from '../../common/ConfigStepBase';
import { ValidationError, ConfigurationService } from '../../services/EBSConfigurationService';
import { ConfigurationState } from '../../services/ConfigurationStateService';
import { ActiveConfig, ExtensionConfiguration } from '../../common/EBSTypes';
import * as ServerConfig from '../../common/ServerConfig';
import { AchievementsService } from '../../services/EBSAchievementsService';

type ConfigSteam_01_WebApiKeyState = {
    isSyntaxValid: boolean,
    isSyntaxError: boolean,
    isValidating: boolean,
    isKeyValid: boolean,
    enteredApiKey: string,
    errors: ValidationError[],
}

export default class ConfigSteam_01_WebAPIKey extends Base.ConfigStepBase<Base.ConfigStepBaseProps, ConfigSteam_01_WebApiKeyState> {
    state: ConfigSteam_01_WebApiKeyState = {
        isSyntaxValid: false,
        isSyntaxError: false,
        isValidating: false,
        isKeyValid: false,
        enteredApiKey: '',
        errors: [],
    }

    formatRegexp = /^[0-9a-f]+$/i;
    formatFullMatchRegexp = (/^[0-9a-f]{32}$/i);

    constructor(props: Base.ConfigStepBaseProps) {
        super(props);

        this.onChangeWebApiValue = this.onChangeWebApiValue.bind(this);
        this.changeWebApiValue = this.changeWebApiValue.bind(this);
    }

    componentDidMount = () => {
        let currentConfig = ConfigurationState.currentConfiguration;
        this.changeWebApiValue(currentConfig.steamConfig.webApiKey);
    }

    onChangeWebApiValue = (e: React.SyntheticEvent<HTMLInputElement>) => {
        this.changeWebApiValue(e.currentTarget.value);
    }

    changeWebApiValue = (value: string) => {
        let formatCheck = this.formatFullMatchRegexp.test(value);
        let isSyntaxValid = this.formatRegexp.test(value);
        this.setState({
            isSyntaxValid: formatCheck,
            isSyntaxError: !isSyntaxValid,
            enteredApiKey: value,
        });
    }

    onContinue = async (e: React.SyntheticEvent<HTMLInputElement>) => {
        this.setState({
            isValidating: true
        });

        const configuration: ExtensionConfiguration = {
            activeConfig: ActiveConfig.Steam,
            xBoxLiveConfig: null,
            version: ServerConfig.EBSVersion,
            steamConfig: {
                webApiKey: this.state.enteredApiKey,
                locale: null,
                steamId: null,
                appId: null,
            }
        }

        let errors = await ConfigurationService.validateConfiguration(configuration);
        errors = errors.filter(e => e.path == "SteamConfig.WebApiKey");

        this.setState({
            errors: errors,
            isValidating: false,
        });

        if (this.state.errors.length == 0)
        {
            this.props.onValid(this, this.props.nextState);
            let newConfig = await ConfigurationService.setConfiguration(configuration);
            
            ConfigurationState.currentConfiguration.steamConfig.webApiKey = this.state.enteredApiKey;
        }
    }

    render(){
        let isContinueEnabled = this.state.isSyntaxValid && !this.state.isValidating;
        return [
            <label htmlFor="webApiKey">Steam WebApi Key</label>,
            <input name="webApiKey" type="text" pattern="[0-9a-fA-F]{32}" value={this.state.enteredApiKey} placeholder="Enter your Steam WebAPI key" onChange={this.onChangeWebApiValue} className={this.state.isSyntaxValid ? '' : 'sf1-invalid'} />,
            <ul>
                {this.state.errors.map((error, i) => (
                    <li key={error.path + '_' + i}>
                        {error.path}: {error.errorDescription}
                    </li>
                ))}
            </ul>,
            <input type="button" value="Continue" disabled={!isContinueEnabled} onClick={this.onContinue} />
        ]
    }
}
