// TwitchAchievementTrackerFrontend/src/components/GameCard/GameCard.svelte
<script lang="ts">
import type { TitleInfo } from "../../common/EBSTypes";

export let titleInfo: TitleInfo

</script>

<div class="card small">
    <h2 class="section">{titleInfo.productTitle}</h2>
    <img class="section media" src={titleInfo.logoUri} alt={`${titleInfo.productTitle} Logo`} />
    <slot name="buttonSection"></slot>
</div>

// TwitchAchievementTrackerFrontend/src/components/GameCard/GameCard.tsx
import * as React from "react";
import { TitleInfo } from "../../common/EBSTypes";
import '../../../public/mini-default.min.css';

type GameCardProps = {
    titleInfo: TitleInfo,
    buttonSection: React.ReactNode,
}

export default class GameCard extends React.Component<GameCardProps, any> {
    constructor(props: GameCardProps){
        super(props);
    }

    render(){
        return (
            <div className="card small">
                <h2 className="section">{this.props.titleInfo.productTitle}</h2>
                <img className="section media" src={this.props.titleInfo.logoUri}></img>
                {this.props.buttonSection}
            </div>
        );
    }
}
