// TwitchAchievementTrackerFrontend/src/components/ConfigXBL_04_Locale/ConfigXBL_04_Locale.tsx
import * as React from 'react';
import * as Base from '../../common/ConfigStepBase';
import { ConfigurationService } from '../../services/EBSConfigurationService';
import { SupportedLanguage } from '../../common/EBSTypes';
import ConfigXBL_05_Confirm from '../ConfigXBL_05_Confirm/ConfigXBL_05_Confirm';


interface ConfigXBL_04_LocaleProps extends Base.ConfigStepBaseProps {
    xApiKey: string,
    streamerXuid: string,
    titleId: string,
}

type ConfigXBL_04_LocaleState = {
    supportedLanguages: SupportedLanguage[],
    selectedLanguage: SupportedLanguage,
    isLoading: boolean,
    isConfirmed: boolean,
}

export default class ConfigXBL_04_Locale extends Base.ConfigStepBase<ConfigXBL_04_LocaleProps, ConfigXBL_04_LocaleState> {
    state: ConfigXBL_04_LocaleState = {
        supportedLanguages: [ { langCode: '', displayName: "Loading..." } ],
        selectedLanguage: null,
        isLoading: true,
        isConfirmed: false,
    };

    constructor(props: ConfigXBL_04_LocaleProps) {
        super(props);
        this.onContinue = this.onContinue.bind(this);
    }

    componentDidMount = () => {
        let currentLocale = this.props.savedConfiguration?.xBoxLiveConfig?.locale;
        
        ConfigurationService.getXBoxLiveSupportedLanguages(this.props.titleId, this.props.xApiKey)
            .then(languages => {
                this.setState({
                    supportedLanguages: [{ langCode: '', displayName: "Select language ..."}].concat(languages),
                    selectedLanguage: currentLocale ? languages.find(l => l.langCode == currentLocale) : null,
                    isLoading: false,
                });
            });
    }

    onSelect = (e: React.ChangeEvent<HTMLSelectElement>) => {
        this.setState({
            supportedLanguages: this.state.supportedLanguages,
            selectedLanguage: this.state.supportedLanguages.find(l => l.langCode == e.currentTarget.value),
        })
    }

    onResetLanguage = () => {
        this.setState({
            selectedLanguage: null,
        });
    }

    onContinue = () => {
        this.setState({
            isConfirmed: true,
        });
    }

    unvalidate = () => {
        this.setState({
            isConfirmed: false,
        });
    }

    render(){
        const isContinueEnabled = this.state.selectedLanguage;
        let selection;

        if (this.state.isConfirmed)
        {
            return (
                <ConfigXBL_05_Confirm
                    savedConfiguration={this.props.savedConfiguration}
                    onValidate={this.props.onValidate}
                    onBack={this.unvalidate}
                    xApiKey={this.props.xApiKey}
                    streamerXuid={this.props.streamerXuid}
                    titleId={this.props.titleId}
                    locale={this.state.selectedLanguage.langCode} />
            )
        }
        
        if (this.state.isLoading)
        {
            selection = (
                <div className="card">
                    <div className="spinner"></div>
                </div>
            )
        }
        else if (this.state.selectedLanguage)
        {
            selection = (
                <div className="card">
                    <h2>{this.state.selectedLanguage.displayName}</h2>
                    <input type="button" className="section" name="LanguageChange" value="Change" onClick={this.onResetLanguage} />
                </div>
            )
        }
        else if (this.state.supportedLanguages)
        {
            selection = (
                <div className="card">
                    <select name="language" className="selectLanguage" onChange={this.onSelect}>
                        {
                            this.state.supportedLanguages.map((language) => (
                                <option value={language.langCode}>{language.displayName}</option>
                            ))
                        }
                    </select>
                </div>
            )
        }

        return [
            selection,
            <input type="button" value="Back" onClick={this.onBack} />,
            <input type="button" disabled={!isContinueEnabled} value="Continue" onClick={this.onContinue} />
        ]
    }
}

// TwitchAchievementTrackerFrontend/src/components/ConfigXBL_04_Locale/ConfigXBL_04_Locale.svelte
<script lang="ts">
import { ConfigurationService } from "../../services/EBSConfigurationService"
import type { ExtensionConfiguration, SupportedLanguage } from "../../common/EBSTypes"
import ConfigXBL_05_Confirm from "../ConfigXBL_05_Confirm/ConfigXBL_05_Confirm.svelte"

export let onValidate: (e: any, configuration: ExtensionConfiguration) => void
export let onBack: (e: any) => void
export let savedConfiguration: ExtensionConfiguration
export let xApiKey: string
export let streamerXuid: string
export let titleId: string

let supportedLanguages: SupportedLanguage[] = [ { langCode: '', displayName: "Loading..." } ]
let selectedLanguage: SupportedLanguage = null
let isLoading: boolean = true
let isConfirmed: boolean = false

function onSelect(value: string)
{
    supportedLanguages = supportedLanguages
    selectedLanguage = supportedLanguages.find(l => l.langCode == value)
}

function onResetLanguage()
{
    selectedLanguage = null
}

function onContinue()
{
    isConfirmed = true
}

function unvalidate()
{
    isConfirmed = false
}

const currentLocale = savedConfiguration?.xBoxLiveConfig?.locale;

ConfigurationService.getXBoxLiveSupportedLanguages(titleId, xApiKey)
    .then(languages => {
        supportedLanguages = [{ langCode: '', displayName: "Select language ..."}].concat(languages)
        selectedLanguage = currentLocale ? languages.find(l => l.langCode == currentLocale) : null
        isLoading = false
    });

let isContinueEnabled: boolean
$: isContinueEnabled = selectedLanguage != null
</script>

{#if isConfirmed}
    <ConfigXBL_05_Confirm
        savedConfiguration={savedConfiguration}
        onValidate={onValidate}
        onBack={unvalidate}
        xApiKey={xApiKey}
        streamerXuid={streamerXuid}
        titleId={titleId}
        locale={selectedLanguage.langCode} />
{:else}
    {#if isLoading}
        <div class="card">
            <div class="spinner"></div>
        </div>
    {:else if selectedLanguage != null}
        <div class="card">
            <h2>{selectedLanguage.displayName}</h2>
            <input type="button" class="section" name="LanguageChange" value="Change" on:click={onResetLanguage} />
        </div>
    {:else if supportedLanguages != null}
        <div class="card">
            <select name="language" class="selectLanguage" on:change={e => onSelect(e.currentTarget.value)}>
            {#each supportedLanguages as language}
                <option value={language.langCode}>{language.displayName}</option>
            {/each}
            </select>
        </div>
    {/if}
    <input type="button" value="Back" on:click={onBack} />
    <input type="button" disabled={!isContinueEnabled} value="Continue" on:click={onContinue} />
{/if}
