// TwitchAchievementTrackerFrontend/src/components/VideoOverlay/VideoOverlay.tsx
import * as React from 'react';
import './VideoOverlay.scss';
import { AchievementSummary, Achievement, TitleInfo, ActiveConfig } from '../../common/EBSTypes';
import { AchievementsService } from '../../services/EBSAchievementsService';
import Cup from '../../../assets/cup.svg';
import Logo from '../../../assets/logo.png';
import { Twitch } from '../../services/TwitchService';
import AchievementsList from '../AchievementsList/AchievementsList';

type VideoOverlayState = {
    isCollapsed: boolean,
    isConfigurationValid: boolean,
    titleInfo: TitleInfo,
    achievementsSummary: AchievementSummary,
    achievementsDetails: Achievement[],
}

export default class VideoOverlay extends React.Component<any, VideoOverlayState> {
    state: VideoOverlayState = {
        isCollapsed: true,
        isConfigurationValid: false,
        titleInfo: null,
        achievementsSummary: null,
        achievementsDetails: []
    }

    constructor(props: any){
        super(props);

        this.togglePanel = this.togglePanel.bind(this);
        this.refreshAll = this.refreshAll.bind(this);
        this.refreshSummary = this.refreshSummary.bind(this);
    }

    componentDidMount = () => {
        this.refreshAll();
        setInterval(this.refreshSummary, 60000);

        Twitch.listen("broadcast", (_target, _contentType, messageStr) => {
            let message = JSON.parse(messageStr);
            let configToken = AchievementsService.configuration.content;
            
            switch (message.type) {
                case "refresh":
                    this.refreshAll();
                    break;
                case "set-config":
                    if (message.configToken != configToken)
                    {
                        AchievementsService.configuration.content = message.configToken;
                        AchievementsService.configuration.version = message.version;
                        this.refreshAll();
                    }
                    break;
                default:
                    break;
            }
        });
    }

    togglePanel = (_e: React.SyntheticEvent<HTMLElement>) => {
        if (! this.state.isConfigurationValid) return;

        this.setState({
            isCollapsed: !this.state.isCollapsed
        })
        if (! this.state.isCollapsed)
        {
            this.refreshSummary();
        }
    }

    refreshAll = async () => {
        let titleInfoPromise = AchievementsService.getTitleInfo();
        AchievementsService.getSummary().then(summary => this .setState({achievementsSummary: summary}));
        AchievementsService.getAchievements().then(achievements => this .setState({achievementsDetails: achievements}));

        try {
            let titleInfo = await titleInfoPromise;
            this.setState({
                isConfigurationValid: true,
                titleInfo: titleInfo,
            });
        }
        catch(error)
        {
            this.setState({
                isConfigurationValid: false,
            });
        }
    }

    refreshSummary = async () => {
        let summaryPromise = AchievementsService.getSummary();
        let achievementsPromise = this.state.isCollapsed ? Promise.resolve(this.state.achievementsDetails) : AchievementsService.getAchievements();

        this.setState({
            achievementsSummary: await summaryPromise,
            achievementsDetails: await achievementsPromise,
        });
    }

    render(){
        let percentage = this.state.achievementsSummary ? (this.state.achievementsSummary.completed / this.state.achievementsSummary.total) * 100.0 : 0.0;
        let completedCount = this.state.achievementsSummary?.completed ?? 0;
        let totalCount = this.state.achievementsSummary?.total ?? 0;
        let platformClass = this.state.titleInfo?.platform == ActiveConfig.Steam ?  "steam" : "xboxlive";
        let logoClassName = "gameLogo noselect " + platformClass;

        return (
            <div className={this.state.isCollapsed ? "overlayBox collapsed" : "overlayBox open"}>
                <div className={logoClassName} onClick={this.togglePanel} style={{backgroundImage: `url(${this.state.titleInfo?.logoUri ?? Logo})`}}>
                    <div className="summaryWidget">
                        { this.state.achievementsSummary ? percentage.toFixed(0) + '%' : ''}
                    </div>
                </div>
                <div id="achievementsPanel" className={platformClass}>
                    <div className="card-container">
                        <h2 id="gameTitle">
                            {this.state.titleInfo?.productTitle ?? "Game"}
                        </h2>
                        <div id="completionHeadline">
                            <span className="percentage">{percentage.toPrecision(2)}%</span>
                            <img src={Cup} alt="achievements" />
                            <span className="completedCount">{completedCount}</span>/<span className="totalCount">{totalCount}</span> 
                        </div>
                    </div>
                    <AchievementsList achievements={this.state.achievementsDetails} platform={this.state.titleInfo?.platform} />
                </div>
            </div>
        )
    }
}

// TwitchAchievementTrackerFrontend/src/components/VideoOverlay/VideoOverlay.svelte
<script lang="ts">
import { type Achievement, type AchievementSummary, ActiveConfig, type TitleInfo } from '../../common/EBSTypes';
import AchievementsList from '../AchievementsList/AchievementsList.svelte'

import Cup from '../../../assets/cup.svg';
import Logo from '../../../assets/logo.png';
import { AchievementsService } from '../../services/EBSAchievementsService'
import { Twitch } from '../../services/TwitchService';

let isCollapsed: boolean = true
let isConfigurationValid: boolean = false
let titleInfo: TitleInfo | null = null
let achievementsSummary: AchievementSummary | null = null
let achievementsDetails: Achievement[] = []

let refreshAll = async () => {
    let titleInfoPromise = AchievementsService.getTitleInfo()
    AchievementsService.getSummary().then(summary => achievementsSummary = summary)
    AchievementsService.getAchievements().then(achievements => achievementsDetails = achievements)

    try {
        titleInfo = await titleInfoPromise
        isConfigurationValid = true
    }
    catch(error)
    {
        isConfigurationValid = false
    }
}

let refreshSummary = async () => {
    let summaryPromise = AchievementsService.getSummary();
    let achievementsPromise = isCollapsed ? Promise.resolve(achievementsDetails) : AchievementsService.getAchievements();

    achievementsSummary = await summaryPromise
    achievementsDetails = await achievementsPromise
}

function togglePanel()
{
    if (! isConfigurationValid) return;

    isCollapsed = !isCollapsed
    if (! isCollapsed)
    {
        refreshSummary();
    }
}

Twitch.listen("broadcast", (_target, _contentType, messageStr) => {
    let message = JSON.parse(messageStr);
    let configToken = AchievementsService.configuration!.content;
    
    switch (message.type) {
        case "refresh":
            refreshAll();
            break;
        case "set-config":
            if (message.configToken != configToken)
            {
                AchievementsService.configuration!.content = message.configToken;
                AchievementsService.configuration!.version = message.version;
                refreshAll();
            }
            break;
        default:
            break;
    }
});

refreshAll()
setInterval(refreshSummary, 60000)

let percentage:number = 0.0
let completedCount:number = 0
let totalCount:number = 0
let platformClass = ""
let logoClassName = ""
let logoUri = `url(${Logo})`

$:{
    percentage = achievementsSummary ? (achievementsSummary.completed / achievementsSummary.total) * 100.0 : 0.0
    completedCount = achievementsSummary?.completed ?? 0
    totalCount = achievementsSummary?.total ?? 0
    platformClass = titleInfo?.platform == ActiveConfig.Steam ?  "steam" : "xboxlive"
    logoClassName = "gameLogo noselect " + platformClass
    logoUri = `url(${titleInfo?.logoUri ?? Logo})`
}
</script>

<style lang="scss">
:global{
    @import "./VideoOverlay.scss";
}
</style>

<div class={isCollapsed ? "overlayBox collapsed" : "overlayBox open"}>
    <div class={logoClassName} on:click="{togglePanel}" style:background-image={logoUri}>
        <div class="summaryWidget">
            { achievementsSummary ? percentage.toFixed(0) + '%' : ''}
        </div>
    </div>
    <div id="achievementsPanel" class={platformClass}>
        <div class="card-container">
            <h2 id="gameTitle">
                {titleInfo?.productTitle ?? "Game"}
            </h2>
            <div id="completionHeadline">
                <span class="percentage">{percentage.toFixed(0)}%</span>
                <img src={Cup} alt="achievements" />
                <span class="completedCount">{completedCount}</span>/<span class="totalCount">{totalCount}</span> 
            </div>
        </div>
        <AchievementsList achievements={achievementsDetails} platform={titleInfo?.platform ?? ActiveConfig.None} />
    </div>
</div>
