// ReactTypescript/src/components/ConfigSteam_03_AppId/ConfigSteam_03_AppId.tsx
import * as React from 'react';
import * as Base from '../../common/ConfigStepBase'
import { AchievementsService } from '../../services/EBSAchievementsService';
import { ConfigurationState } from '../../services/ConfigurationStateService';
import { ConfigurationService } from '../../services/EBSConfigurationService';
import * as webpack from 'webpack';
import { TitleInfo } from '../../common/EBSTypes';

type ConfigSteam_02_AppIdState = {
    titleSearch: string;
    isLoading: boolean;
    ownedApps: TitleInfo[];
    filteredApps: TitleInfo[];
    selectedTitle: TitleInfo;
}

export default class ConfigSteam_02_AppId extends Base.ConfigStepBase<Base.ConfigStepBaseProps, ConfigSteam_02_AppIdState> {
    state: ConfigSteam_02_AppIdState = {
        titleSearch: '',
        isLoading: true,
        ownedApps: [],
        filteredApps: [],
        selectedTitle: null,
    }

    constructor(props: Base.ConfigStepBaseProps){
        super(props);

        this.onContinue = this.onContinue.bind(this);
        this.onChangeTitleSearch = this.onChangeTitleSearch.bind(this);
        this.onSelectTitle = this.onSelectTitle.bind(this);
    }

    componentDidMount = () => {
        let steamId = ConfigurationState.currentConfiguration.steamConfig.steamId;
        let currentTitle = ConfigurationState.currentConfiguration.steamConfig.appId;

        ConfigurationService.getSteamOwnedGames(steamId, ConfigurationState.currentConfiguration.steamConfig.webApiKey)
        .then(gameList => {
            let gameInfo: TitleInfo = null;
            if (currentTitle)
            {
                gameInfo = gameList.find(g => g.titleId == currentTitle);
            }
            
            this.setState({
                isLoading: false,
                filteredApps: gameList,
                ownedApps: gameList,
                selectedTitle: gameInfo,
            });
        });
    }

    onContinue = async (e: React.SyntheticEvent<HTMLInputElement>) => {
        ConfigurationState.currentConfiguration.steamConfig.appId = this.state.selectedTitle.titleId;
        this.props.onValid(this, this.props.nextState);
    }

    onChangeTitleSearch = async (e: React.ChangeEvent<HTMLInputElement>) => {
        let titleSearch = e.currentTarget.value.toLowerCase();
        this.setState({
            titleSearch: titleSearch,
            filteredApps: this.state.ownedApps.filter(app => app.productTitle.toLowerCase().search(titleSearch) != -1),
            ownedApps: this.state.ownedApps
        });
    }

    onSelectTitle = (e: React.MouseEvent<HTMLLIElement>) => {
        let titleId = e.currentTarget.attributes.getNamedItem("itemId").value;
        let titleInfo = this.state.ownedApps.find(t => t.titleId == titleId);

        this.setState({
            titleSearch: "",
            filteredApps: this.state.ownedApps,
            ownedApps: this.state.ownedApps,
            selectedTitle: titleInfo,
        });

        // Validate and move on
    }

    onResetTitle = (e: React.MouseEvent<HTMLInputElement>) => {
        this.setState({
            titleSearch: "",
            filteredApps: this.state.ownedApps,
            ownedApps: this.state.ownedApps,
            selectedTitle: null,
        });
    }

    render(){
        const isContinueEnabled = this.state.selectedTitle;
        let selection;
        if (this.state.selectedTitle)
        {
            selection = (
                <div className="card">
                    <h2 className="section">{this.state.selectedTitle.productTitle}</h2>
                    <img className="section" src={this.state.selectedTitle.logoUri}></img>
                    <input type="button" className="section" name="TitleChange" value="Change" onClick={this.onResetTitle} />
                </div>
            )
        }
        else
        {
            selection = [
                <input name="titleSearch" type="text" placeholder="Filter your Steam games" onChange={this.onChangeTitleSearch} />,
                <ul className="searchResult">
                    {
                        this.state.filteredApps.map((titleInfo, i) => (
                            <li itemID={titleInfo.titleId} key={titleInfo.titleId} onClick={this.onSelectTitle}><img src={titleInfo.logoUri}></img> {titleInfo.productTitle}</li>
                        ))
                    }
                </ul>
            ]
        }

        return [
            <label htmlFor="titleSearch">Game Title</label>,
            selection,
            <input type="button" value="Continue" disabled={!isContinueEnabled} onClick={this.onContinue} />
        ]
    }
}

// TwitchAchievementTrackerFrontend/src/components/ConfigSteam_03_AppId/ConfigSteam_03_AppId.svelte
<script lang="ts">
import { EBSVersion } from "../../common/ServerConfig"
import { ActiveConfig, type ExtensionConfiguration, type TitleInfo } from "../../common/EBSTypes"
import { ConfigurationService, type ValidationError } from "../../services/EBSConfigurationService"
import ValidationErrorList from "../ValidationErrorList/ValidationErrorList.svelte"
import GameCard from "../GameCard/GameCard.svelte"
import ConfigSteam_04_Locale from "../ConfigSteam_04_Locale/ConfigSteam_04_Locale.svelte"

export let onValidate: (e: any, configuration: ExtensionConfiguration) => void
export let onBack: (e: any) => void
export let savedConfiguration: ExtensionConfiguration
export let webApiKey: string
export let steamProfileId: string

let titleSearch: string = ''
let isLoading: boolean = true
let isConfirmed: boolean = false
let ownedApps: TitleInfo[] = []
let filteredApps: TitleInfo[] = []
let selectedTitle: TitleInfo | null = null
let errors: ValidationError[] = []

async function onContinue()
{
    isConfirmed = true
}

async function onChangeTitleSearch(value: string)
{
    titleSearch = value.toLowerCase()
    filteredApps = ownedApps.filter(app => app.productTitle.toLowerCase().search(titleSearch) != -1)
}

async function onSelectTitle(titleId: string)
{
    let titleInfo = ownedApps.find(t => t.titleId == titleId) ?? null;

    isLoading = true
    titleSearch = ""
    filteredApps = ownedApps
    selectedTitle = titleInfo!

    // Validate and move on
    const configuration: ExtensionConfiguration = {
        activeConfig: ActiveConfig.Steam,
        steamConfig: {
            steamId: steamProfileId,
            webApiKey: webApiKey,
            appId: titleInfo!.titleId,
            locale: "english",
        },
        version: EBSVersion,
        xBoxLiveConfig: null
    }

    let newErrors = await ConfigurationService.validateConfiguration(configuration);
    errors = newErrors.filter(e => e.path == "SteamConfig.WebApiKey" || e.path == "SteamConfig.SteamId");
    isLoading = false
    selectedTitle = errors.length == 0 ? titleInfo : null
}

function onResetTitle()
{
    titleSearch = "",
    filteredApps = ownedApps
    selectedTitle = null
}

function unvalidate()
{
    isConfirmed = false
}


ConfigurationService.getSteamOwnedGames(steamProfileId, webApiKey)
    .then(gameList => {
        let gameInfo: TitleInfo | null = null;
        if (selectedTitle)
        {
            gameInfo = gameList.find(g => g.titleId == selectedTitle!.titleId) ?? null;
        }
        
        isLoading = false
        filteredApps = gameList
        ownedApps = gameList
        selectedTitle = gameInfo
    });
let isContinueEnabled: boolean
$: isContinueEnabled = selectedTitle != null
</script>

{#if isConfirmed}
    <ConfigSteam_04_Locale
        savedConfiguration={savedConfiguration}
        onValidate={onValidate}
        onBack={unvalidate}
        webApiKey={webApiKey}
        steamProfileId={steamProfileId}
        steamAppId={selectedTitle?.titleId ?? ""}/>
{:else}
    <ValidationErrorList errors={errors} />
    {#if isLoading}
        <div class="card">
            <div class="spinner"></div>
        </div>
    {:else if selectedTitle}
        <GameCard titleInfo={selectedTitle}>
            <input slot="buttonSection" type="button" class="section" name="TitleChange" value="Change" on:click={onResetTitle} />
        </GameCard>
    {:else}
        <label for="titleSearch">Owned Game list</label>
        <input name="titleSearch" type="text" placeholder="Filter your Steam games" on:change={e => onChangeTitleSearch(e.currentTarget.value)} />
        <div class="searchResult container">
            <div class="row">
                {#each filteredApps as titleInfo}
                    <GameCard titleInfo={titleInfo}>
                        <input slot="buttonSection" class="section" type="button" name="steamTitleChange" value="Select" on:click={_e => onSelectTitle(titleInfo.titleId)} />
                    </GameCard>
                {/each}
            </div>
        </div>
    {/if}
    <input type="button" value="Back" on:click={onBack} />
    <input type="button" value="Continue" disabled={!isContinueEnabled} on:click={onContinue} />
{/if}
