// TwitchAchievementTrackerFrontend/src/components/ConfigSteam_03_AppId/ConfigSteam_03_AppId.svelte
<script lang="ts">
import { EBSVersion } from "../../common/ServerConfig"
import { ActiveConfig, type ExtensionConfiguration, type TitleInfo } from "../../common/EBSTypes"
import { ConfigurationService, type ValidationError } from "../../services/EBSConfigurationService"
import ValidationErrorList from "../ValidationErrorList/ValidationErrorList.svelte"
import GameCard from "../GameCard/GameCard.svelte"
import ConfigSteam_04_Locale from "../ConfigSteam_04_Locale/ConfigSteam_04_Locale.svelte"

export let onValidate: (e: any, configuration: ExtensionConfiguration) => void
export let onBack: (e: any) => void
export let savedConfiguration: ExtensionConfiguration
export let webApiKey: string
export let steamProfileId: string

let titleSearch: string = ''
let isLoading: boolean = true
let isConfirmed: boolean = false
let ownedApps: TitleInfo[] = []
let filteredApps: TitleInfo[] = []
let selectedTitle: TitleInfo | null = null
let errors: ValidationError[] = []

async function onContinue()
{
    isConfirmed = true
}

async function onChangeTitleSearch(value: string)
{
    titleSearch = value.toLowerCase()
    filteredApps = ownedApps.filter(app => app.productTitle.toLowerCase().search(titleSearch) != -1)
}

async function onSelectTitle(titleId: string)
{
    let titleInfo = ownedApps.find(t => t.titleId == titleId) ?? null;

    isLoading = true
    titleSearch = ""
    filteredApps = ownedApps
    selectedTitle = titleInfo!

    // Validate and move on
    const configuration: ExtensionConfiguration = {
        activeConfig: ActiveConfig.Steam,
        steamConfig: {
            steamId: steamProfileId,
            webApiKey: webApiKey,
            appId: titleInfo!.titleId,
            locale: "english",
        },
        version: EBSVersion,
        xBoxLiveConfig: null
    }

    let newErrors = await ConfigurationService.validateConfiguration(configuration);
    errors = newErrors.filter(e => e.path == "SteamConfig.WebApiKey" || e.path == "SteamConfig.SteamId");
    isLoading = false
    selectedTitle = errors.length == 0 ? titleInfo : null
}

function onResetTitle()
{
    titleSearch = "",
    filteredApps = ownedApps
    selectedTitle = null
}

function unvalidate()
{
    isConfirmed = false
}


ConfigurationService.getSteamOwnedGames(steamProfileId, webApiKey)
    .then(gameList => {
        let gameInfo: TitleInfo | null = null;
        if (selectedTitle)
        {
            gameInfo = gameList.find(g => g.titleId == selectedTitle!.titleId) ?? null;
        }
        
        isLoading = false
        filteredApps = gameList
        ownedApps = gameList
        selectedTitle = gameInfo
    });
let isContinueEnabled: boolean
$: isContinueEnabled = selectedTitle != null
</script>

{#if isConfirmed}
    <ConfigSteam_04_Locale
        savedConfiguration={savedConfiguration}
        onValidate={onValidate}
        onBack={unvalidate}
        webApiKey={webApiKey}
        steamProfileId={steamProfileId}
        steamAppId={selectedTitle?.titleId ?? ""}/>
{:else}
    <ValidationErrorList errors={errors} />
    {#if isLoading}
        <div class="card">
            <div class="spinner"></div>
        </div>
    {:else if selectedTitle}
        <GameCard titleInfo={selectedTitle}>
            <input slot="buttonSection" type="button" class="section" name="TitleChange" value="Change" on:click={onResetTitle} />
        </GameCard>
    {:else}
        <label for="titleSearch">Owned Game list</label>
        <input name="titleSearch" type="text" placeholder="Filter your Steam games" on:change={e => onChangeTitleSearch(e.currentTarget.value)} />
        <div class="searchResult container">
            <div class="row">
                {#each filteredApps as titleInfo}
                    <GameCard titleInfo={titleInfo}>
                        <input slot="buttonSection" class="section" type="button" name="steamTitleChange" value="Select" on:click={_e => onSelectTitle(titleInfo.titleId)} />
                    </GameCard>
                {/each}
            </div>
        </div>
    {/if}
    <input type="button" value="Back" on:click={onBack} />
    <input type="button" value="Continue" disabled={!isContinueEnabled} on:click={onContinue} />
{/if}

// TwitchAchievementTrackerFrontend/src/components/ConfigSteam_03_AppId/ConfigSteam_03_AppId.tsx
import * as React from 'react';
import * as Base from '../../common/ConfigStepBase'
import { ConfigurationService, ValidationError } from '../../services/EBSConfigurationService';
import { TitleInfo, ExtensionConfiguration, ActiveConfig } from '../../common/EBSTypes';
import GameCard from '../GameCard/GameCard';
import ConfigSteam_04_Locale from '../ConfigSteam_04_Locale/ConfigSteam_04_Locale';
import { EBSVersion } from '../../common/ServerConfig';
import ValidationErrorList from '../ValidationErrorList/ValidationErrorList';


interface ConfigSteam_03_AppIdProps extends Base.ConfigStepBaseProps {
    webApiKey: string,
    steamProfileId: string,
}

type ConfigSteam_03_AppIdState = {
    titleSearch: string;
    isLoading: boolean;
    isConfirmed: boolean;
    ownedApps: TitleInfo[];
    filteredApps: TitleInfo[];
    selectedTitle: TitleInfo;
    errors: ValidationError[];
}

export default class ConfigSteam_03_AppId extends Base.ConfigStepBase<ConfigSteam_03_AppIdProps, ConfigSteam_03_AppIdState> {
    state: ConfigSteam_03_AppIdState = {
        titleSearch: '',
        isLoading: true,
        isConfirmed: false,
        ownedApps: [],
        filteredApps: [],
        selectedTitle: null,
        errors: [],
    }

    constructor(props: ConfigSteam_03_AppIdProps){
        super(props);

        this.onContinue = this.onContinue.bind(this);
        this.onChangeTitleSearch = this.onChangeTitleSearch.bind(this);
        this.onSelectTitle = this.onSelectTitle.bind(this);
    }

    componentDidMount = () => {
        ConfigurationService.getSteamOwnedGames(this.props.steamProfileId, this.props.webApiKey)
        .then(gameList => {
            let gameInfo: TitleInfo = null;
            if (this.state.selectedTitle)
            {
                gameInfo = gameList.find(g => g.titleId == this.state.selectedTitle.titleId);
            }
            
            this.setState({
                isLoading: false,
                filteredApps: gameList,
                ownedApps: gameList,
                selectedTitle: gameInfo,
            });
        });
    }

    onContinue = async () => {
        this.setState({
            isConfirmed: true,
        });
    }

    onChangeTitleSearch = async (e: React.ChangeEvent<HTMLInputElement>) => {
        let titleSearch = e.currentTarget.value.toLowerCase();
        this.setState({
            titleSearch: titleSearch,
            filteredApps: this.state.ownedApps.filter(app => app.productTitle.toLowerCase().search(titleSearch) != -1),
            ownedApps: this.state.ownedApps
        });
    }

    onSelectTitle = async (_e: React.MouseEvent<HTMLElement>, titleId: string) => {
        let titleInfo = this.state.ownedApps.find(t => t.titleId == titleId);

        this.setState({
            isLoading: true,
            titleSearch: "",
            filteredApps: this.state.ownedApps,
            ownedApps: this.state.ownedApps,
            selectedTitle: titleInfo,
        });

        // Validate and move on
        const configuration: ExtensionConfiguration = {
            activeConfig: ActiveConfig.Steam,
            steamConfig: {
                steamId: this.props.steamProfileId,
                webApiKey: this.props.webApiKey,
                appId: titleInfo.titleId,
                locale: "english",
            },
            version: EBSVersion,
            xBoxLiveConfig: null
        }

        let errors = await ConfigurationService.validateConfiguration(configuration);
        errors = errors.filter(e => e.path == "SteamConfig.WebApiKey" || e.path == "SteamConfig.SteamId");

        this.setState({
            isLoading: false,
            errors: errors,
            selectedTitle: errors.length == 0 ? titleInfo : null,
        });
    }

    onResetTitle = () => {
        this.setState({
            titleSearch: "",
            filteredApps: this.state.ownedApps,
            ownedApps: this.state.ownedApps,
            selectedTitle: null,
        });
    }

    unvalidate = () => {
        this.setState({
            isConfirmed: false,
        });
    }

    render(){
        const isContinueEnabled = this.state.selectedTitle;
        let selection;

        if (this.state.isConfirmed)
        {
            return (
                <ConfigSteam_04_Locale
                    savedConfiguration={this.props.savedConfiguration}
                    onValidate={this.props.onValidate}
                    onBack={this.unvalidate}
                    webApiKey={this.props.webApiKey}
                    steamProfileId={this.props.steamProfileId}
                    steamAppId={this.state.selectedTitle.titleId} />

            );
        }

        if (this.state.isLoading)
        {
            selection = (
                <div className="card">
                    <div className="spinner"></div>
                </div>
            )
        }
        else if (this.state.selectedTitle)
        {
            selection = (
                <GameCard titleInfo={this.state.selectedTitle} buttonSection={<input type="button" className="section" name="TitleChange" value="Change" onClick={this.onResetTitle} />} />
            )
        }
        else
        {
            selection = [
                <label htmlFor="titleSearch">Owned Game list</label>,
                <input name="titleSearch" type="text" placeholder="Filter your Steam games" onChange={this.onChangeTitleSearch} />,,
                <div className="searchResult container">
                    <div className="row">
                    {
                        this.state.filteredApps.map((titleInfo) => (
                            <GameCard titleInfo={titleInfo} buttonSection={<input className="section" type="button" name="steamTitleChange" value="Select" onClick={(e) => this.onSelectTitle(e, titleInfo.titleId)} />} />
                        ))
                    }
                    </div>
                </div>
            ]
        }

        return [
            <ValidationErrorList errors={this.state.errors} />,
            selection,
            <input type="button" value="Back" onClick={this.onBack} />,
            <input type="button" value="Continue" disabled={!isContinueEnabled} onClick={this.onContinue} />
        ]
    }
}
