// TwitchAchievementTrackerFrontend/src/components/CountDown/CountDown.tsx
import * as React from 'react';
import dayjs from 'dayjs';
import duration from 'dayjs/plugin/duration';

dayjs.extend(duration);

interface CountDownProps {
    targetDate: Date,
}

export default class CountDown extends React.Component<CountDownProps, any>
{
    tickInterval: NodeJS.Timeout = null;

    constructor(props: CountDownProps)
    {
        super(props);
    }

    componentDidMount = () => {
        this.tickInterval = setInterval(this.tick, 1000);
    }

    componentWillUnmount = () => {
        clearInterval(this.tickInterval);
        this.tickInterval = null;
    }

    tick = () => {
        this.forceUpdate();
    }

    render(){

        let targetMoment = dayjs(this.props.targetDate);
        let diffToTarget = targetMoment.diff(dayjs());
        let timeToTarget = dayjs.duration(diffToTarget);

        return (
            <div>
                <span className="rounded">
                    {timeToTarget.hours().toString().padStart(2, "0")}
                    </span>
                    :
                    <span className="rounded">
                        {timeToTarget.minutes().toString().padStart(2, "0")}
                    </span>
                    :
                    <span className="rounded">
                        {timeToTarget.seconds().toString().padStart(2, "0")}
                    </span>
            </div>
        )
    }
}

// TwitchAchievementTrackerFrontend/src/components/CountDown/CountDown.svelte
<script lang="ts">
import dayjs from 'dayjs'
import duration from 'dayjs/plugin/duration'
import { onDestroy, onMount } from 'svelte';
dayjs.extend(duration)

export let targetDate: Date

let tickInterval: NodeJS.Timeout = null;
let targetMoment: any
$: targetMoment = dayjs(targetDate)
let diffToTarget: any
let timeToTarget: any

onMount(() => {
    tick()
    tickInterval = setInterval(tick, 1000)
})

onDestroy(() => {
    clearInterval(tickInterval)
    tickInterval = null
})

function tick()
{
    diffToTarget = targetMoment.diff(dayjs())
    timeToTarget = dayjs.duration(diffToTarget)
}

</script>

<div>
    <span class="rounded">
        {timeToTarget?.hours()?.toString()?.padStart(2, "0") ?? "00"}
        </span>
        :
        <span class="rounded">
            {timeToTarget?.minutes()?.toString()?.padStart(2, "0") ?? "00"}
        </span>
        :
        <span class="rounded">
            {timeToTarget?.seconds()?.toString()?.padStart(2, "0") ?? "00"}
        </span>
</div>
