// TwitchAchievementTrackerFrontend/src/components/ConfigSteam_04_Locale/ConfigSteam_04_Locale.tsx
import * as React from 'react';
import * as Base from '../../common/ConfigStepBase'
import { SupportedLanguage } from '../../common/EBSTypes';
import { ConfigurationService } from '../../services/EBSConfigurationService';
import ConfigSteam_05_Confirm from '../ConfigSteam_05_Confirm/ConfigSteam_05_Confirm';

interface ConfigSteam_04_LocaleProps extends Base.ConfigStepBaseProps {
    webApiKey: string,
    steamProfileId: string,
    steamAppId: string,
}

type ConfigSteam_04_LocaleState = {
    isLoading: boolean,
    supportedLanguages: SupportedLanguage[],
    selectedLanguage: SupportedLanguage,
    isConfirmed: boolean,
}

export default class ConfigSteam_04_Locale extends Base.ConfigStepBase<ConfigSteam_04_LocaleProps, ConfigSteam_04_LocaleState> {
    state: ConfigSteam_04_LocaleState = {
        isLoading: true,
        supportedLanguages: [ { langCode: '', displayName: "Loading..." } ],
        selectedLanguage: null,
        isConfirmed: false,
    };

    constructor(props: ConfigSteam_04_LocaleProps) {
        super(props);
        this.onContinue = this.onContinue.bind(this);
    }

    componentDidMount = () => {
        let currentLanguage: string = this.props.savedConfiguration?.steamConfig?.locale;

        ConfigurationService.getSteamSupportedLanguages(this.props.steamAppId, this.props.webApiKey)
            .then(languages => {
                this.setState({
                    isLoading: false,
                    supportedLanguages: [{ langCode: '', displayName: "Select language ..."}].concat(languages),
                    selectedLanguage: currentLanguage ? languages.find(l => l.langCode == currentLanguage) : null,
                });
            });
    }

    onSelect = (e: React.ChangeEvent<HTMLSelectElement>) => {
        this.setState({
            supportedLanguages: this.state.supportedLanguages,
            selectedLanguage: this.state.supportedLanguages.find(l => l.langCode == e.currentTarget.value),
        })
    }

    onResetLanguage = (_e: React.SyntheticEvent<HTMLInputElement>) => {
        this.setState({
            selectedLanguage: null,
        });
    }

    onContinue = (_e: React.SyntheticEvent<HTMLInputElement>) => {
        this.setState({
            isConfirmed: true
        })
    }

    unvalidate = (_e: React.SyntheticEvent<HTMLElement>) => {
        this.setState({
            isConfirmed: false
        });
    }
    
    render(){
        const isContinueEnabled = this.state.selectedLanguage != null;
        let selection;

        if (this.state.isConfirmed)
        {
            return (
                <ConfigSteam_05_Confirm
                    savedConfiguration={this.props.savedConfiguration}
                    onValidate={this.props.onValidate}
                    onBack={this.unvalidate}
                    webApiKey={this.props.webApiKey}
                    steamProfileId={this.props.steamProfileId}
                    steamAppId={this.props.steamAppId}
                    locale={this.state.selectedLanguage.langCode} />
            )
        }

        if (this.state.isLoading)
        {
            selection = (
                <div className="card">
                    <div className="spinner"></div>
                </div>
            )
        }
        else if (this.state.selectedLanguage)
        {
            selection = (
                <div className="card">
                    <h2>{this.state.selectedLanguage.displayName}</h2>
                    <input type="button" className="section" name="LanguageChange" value="Change" onClick={this.onResetLanguage} />
                </div>
            )
        }
        else if (this.state.supportedLanguages)
        {
            selection = (
                <div className="card">
                    <select name="language" className="selectLanguage" onChange={this.onSelect}>
                        {
                            this.state.supportedLanguages.map((language) => (
                                <option value={language.langCode}>{language.displayName}</option>
                            ))
                        }
                    </select>
                </div>
            )
        }

        return [
            selection,
            <input type="button" value="Back" onClick={this.onBack} />,
            <input type="button" disabled={!isContinueEnabled} value="Continue" onClick={this.onContinue} />
        ]
    }
}

// TwitchAchievementTrackerFrontend/src/components/ConfigSteam_04_Locale/ConfigSteam_04_Locale.svelte
<script lang="ts">
import { ConfigurationService } from "../../services/EBSConfigurationService"
import type { ExtensionConfiguration, SupportedLanguage } from "../../common/EBSTypes"
import ConfigSteam_05_Confirm from "../ConfigSteam_05_Confirm/ConfigSteam_05_Confirm.svelte"

export let onValidate: (e: any, configuration: ExtensionConfiguration) => void
export let onBack: (e: any) => void
export let savedConfiguration: ExtensionConfiguration
export let webApiKey: string
export let steamProfileId: string
export let steamAppId: string

let isLoading: boolean =  true
let supportedLanguages: SupportedLanguage[] =  [ { langCode: '', displayName: "Loading..." } ]
let selectedLanguage: SupportedLanguage =  null
let isConfirmed: boolean =  false

function onSelect(value: string)
{
    selectedLanguage = supportedLanguages.find(l => l.langCode == value)
}

function onResetLanguage(_e: any)
{
    selectedLanguage = null
}

function onContinue(_e: any)
{
    isConfirmed = true
}

function unvalidate(_e: any)
{
    isConfirmed = false
}

let currentLanguage: string
$: currentLanguage = savedConfiguration?.steamConfig?.locale

ConfigurationService.getSteamSupportedLanguages(steamAppId, webApiKey)
    .then(languages => {
        isLoading = false
        supportedLanguages = [{ langCode: '', displayName: "Select language ..."}].concat(languages)
        selectedLanguage = currentLanguage ? languages.find(l => l.langCode == currentLanguage) : null
    });

let isContinueEnabled
$: isContinueEnabled = selectedLanguage != null;
</script>


{#if isConfirmed}
<ConfigSteam_05_Confirm
    savedConfiguration={savedConfiguration}
    onValidate={onValidate}
    onBack={unvalidate}
    webApiKey={webApiKey}
    steamProfileId={steamProfileId}
    steamAppId={steamAppId}
    locale={selectedLanguage.langCode} />
{:else}
    {#if isLoading}
        <div class="card">
            <div class="spinner"></div>
        </div>
    {:else if selectedLanguage != null}
        <div class="card">
            <h2>{selectedLanguage.displayName}</h2>
            <input type="button" class="section" name="LanguageChange" value="Change" onClick={onResetLanguage} />
        </div>
    {:else if supportedLanguages != null}
    <div class="card">
        <select name="language" class="selectLanguage" on:change={e => onSelect(e.currentTarget.value)}>
            {#each supportedLanguages as language}
                <option value={language.langCode}>{language.displayName}</option>
            {/each}
        </select>
    </div>
    {/if}
    <input type="button" value="Back" on:click={onBack} />
    <input type="button" disabled={!isContinueEnabled} value="Continue" on:click={onContinue} />
{/if}
