// TwitchAchievementTrackerFrontend/src/components/LiveConfigRoot/LiveConfigRoot.tsx
import * as React from 'react';
import { ConfigurationService, ValidationError } from '../../services/EBSConfigurationService';
import { ExtensionConfiguration, ActiveConfig, RateLimits, TitleInfo } from '../../common/EBSTypes';
import { Twitch } from '../../services/TwitchService';
import { EBSVersion } from '../../common/ServerConfig' 
import { AchievementsService } from '../../services/EBSAchievementsService';
import CountDown from '../CountDown/CountDown';
import './LiveConfigRoot.scss';

interface LiveConfigRootState {
    isLoading: boolean;
    isRefreshing: boolean;
    wasModified: boolean;
    configuration: ExtensionConfiguration;
    titleInfo: TitleInfo;
    errors: ValidationError[];
    xApiRateLimits: RateLimits;
}

export default class LiveConfigRoot extends React.Component<any,LiveConfigRootState>
{
    refreshRateLimitsInterval: NodeJS.Timeout = null;

    state: LiveConfigRootState = {
        isLoading: true,
        isRefreshing: false,
        wasModified: false,
        configuration: null,
        titleInfo: null,
        errors: [],
        xApiRateLimits: null,
    }

    constructor(props: any){
        super(props);

        this.onForceRefresh = this.onForceRefresh.bind(this);
    }

    componentDidMount = async () => {
        let titleInfo: TitleInfo = null;

        await ConfigurationService.configuredPromise;

        let configuration = await ConfigurationService.getConfiguration();
        let validation = await ConfigurationService.validateConfiguration(configuration);
        if (validation.length == 0)
        {
            titleInfo = await AchievementsService.getTitleInfo();
        }

        this.setState({
            isLoading: false,
            configuration: configuration,
            titleInfo: titleInfo,
            errors: validation,
        });
        
        if (configuration.activeConfig == ActiveConfig.XBoxLive)
        {
            this.refreshRateLimit();
            this.refreshRateLimitsInterval = setInterval(this.refreshRateLimit, 1000);
        }
        
        Twitch.listen("broadcast", async (_target, _contentType, messageStr) => {
            let message = JSON.parse(messageStr);
            let configToken = AchievementsService.configuration.content;
            
            switch (message.type) {
                case "refresh":
                    break;
                case "set-config":
                    if (message.configToken != configToken)
                    {
                        AchievementsService.configuration.content = message.configToken;
                        AchievementsService.configuration.version = message.version;
                        ConfigurationService.configuration.content = message.configToken;
                        ConfigurationService.configuration.version = message.version;

                        this.setState({
                            isLoading: true,
                        });
                        let config = await ConfigurationService.getConfiguration();
                        let titleInfo = await AchievementsService.getTitleInfo();

                        this.setState({
                            isLoading: false,
                            configuration: config,
                            titleInfo: titleInfo,
                            errors: validation,
                        });
                        
                        if (config.activeConfig == ActiveConfig.XBoxLive)
                        {
                            if (! this.refreshRateLimitsInterval)
                            {
                                this.refreshRateLimitsInterval = setInterval(this.refreshRateLimit, 1000);
                            }
                        }
                    }
                    break;
                default:
                    break;
            }
        });
    }

    refreshRateLimit = async () => {
        if (this.state.configuration.activeConfig != ActiveConfig.XBoxLive)
        {
            clearInterval(this.refreshRateLimitsInterval);
            this.refreshRateLimitsInterval = null;
            this.setState({
                xApiRateLimits: null
            });
            return;
        }

        let rateLimits = await ConfigurationService.getXApiRateLimits();
        this.setState({
            xApiRateLimits: rateLimits
        });
    }

    onForceRefresh = async () => {
        this.setState({
            isRefreshing: true
        });

        let didChange = await ConfigurationService.forceRefresh();
        if (didChange)
        {
            Twitch.send("broadcast", "application/json", {
                "type": "refresh",
                "version": EBSVersion,
            });
        }

        this.setState({
            isRefreshing: false,
            wasModified: didChange,
        });
    }

    render(){
        if (this.state.isLoading)
        {
            return (
                <div className="card small">
                    <div className="spinner"></div> Loading configuration
                </div>
            )
        }

        return (
            <div className="card small">
                <h3 className="section">Achievements Tracker</h3>
                <div className="section titleinfo row">
                    <div className="col-sm-4" >
                        <img src={this.state.titleInfo.logoUri} />
                    </div>
                    <div className="col-sm-8">
                        <button className="large primary" onClick={this.onForceRefresh} disabled={this.state.isRefreshing}>Force refresh</button>
                    </div>
                </div>
                
                {this.state.xApiRateLimits ? [
                    <div className="section">
                        <h4>xApi.us calls</h4>
                        <div className="row">
                            <div className="col-sm-6">
                                Remaining
                            </div>
                            <div className="col-sm-6">
                                {this.state.xApiRateLimits.remaining}/{this.state.xApiRateLimits.hourlyLimit}
                            </div>
                        </div>
                        <div className="row">
                            <div className="col-sm-6">
                                Resets in
                            </div>
                            <div className="col-sm-6">
                                <CountDown targetDate={this.state.xApiRateLimits.resetTime} />
                            </div>
                        </div>
                    </div>,
                    <div className="section">
                        Force refresh typically uses 1 call.<br/>
                        15 auto-refresh per hour.
                    </div>
                ] : null}
            </div>
        )
    }
}

// TwitchAchievementTrackerFrontend/src/components/LiveConfigRoot/LiveConfigRoot.svelte
<script lang="ts">
import { EBSVersion } from "../../common/ServerConfig";
import { AchievementsService } from "../../services/EBSAchievementsService";
import { Twitch } from "../../services/TwitchService";
import { ActiveConfig, ExtensionConfiguration, RateLimits, TitleInfo } from "../../common/EBSTypes"
import { ConfigurationService, ValidationError } from "../../services/EBSConfigurationService"
import CountDown from "../CountDown/CountDown.svelte";
import { onDestroy, onMount } from "svelte";
    
let isLoading: boolean = true
let isRefreshing: boolean = false
let wasModified: boolean = false
let configuration: ExtensionConfiguration = null
let titleInfo: TitleInfo = null
let errors: ValidationError[] = []
let xApiRateLimits: RateLimits = null

let refreshRateLimitsInterval: NodeJS.Timeout = null


async function refreshRateLimit()
{
    if (configuration.activeConfig != ActiveConfig.XBoxLive)
    {
        clearInterval(refreshRateLimitsInterval)
        refreshRateLimitsInterval = null
        xApiRateLimits = null
        return;
    }

    let rateLimits = await ConfigurationService.getXApiRateLimits()
    xApiRateLimits = rateLimits
}

async function onForceRefresh()
{
    isRefreshing = true

    let didChange = await ConfigurationService.forceRefresh();
    if (didChange)
    {
        Twitch.send("broadcast", "application/json", {
            "type": "refresh",
            "version": EBSVersion,
        });
    }

    isRefreshing = false
    wasModified = didChange
}

onMount(async () => {
    ConfigurationService.configuredPromise.then(async (_context) => {
        configuration = await ConfigurationService.getConfiguration();
        let validation = await ConfigurationService.validateConfiguration(configuration);
        if (validation.length == 0)
        {
            titleInfo = await AchievementsService.getTitleInfo();
        }

        isLoading = false
        errors = validation

        if (configuration.activeConfig == ActiveConfig.XBoxLive)
        {
            refreshRateLimit();
            refreshRateLimitsInterval = setInterval(refreshRateLimit, 1000);
        }

        Twitch.listen("broadcast", async (_target, _contentType, messageStr) => {
            let message = JSON.parse(messageStr);
            let configToken = AchievementsService.configuration.content;
            
            switch (message.type) {
                case "refresh":
                    break;
                case "set-config":
                    if (message.configToken != configToken)
                    {
                        AchievementsService.configuration.content = message.configToken;
                        AchievementsService.configuration.version = message.version;
                        ConfigurationService.configuration.content = message.configToken;
                        ConfigurationService.configuration.version = message.version;

                        isLoading = true
                        
                        let config = await ConfigurationService.getConfiguration();
                        let titleInfo = await AchievementsService.getTitleInfo();

                        isLoading = false
                        configuration = config
                        titleInfo = titleInfo
                        errors = validation
                        
                        if (config.activeConfig == ActiveConfig.XBoxLive)
                        {
                            if (! refreshRateLimitsInterval)
                            {
                                refreshRateLimitsInterval = setInterval(refreshRateLimit, 1000);
                            }
                        }
                    }
                    break;
                default:
                    break;
            }
        });
    })
})

onDestroy(() => {
    if (refreshRateLimitsInterval)
    {
        clearInterval(refreshRateLimitsInterval)
    }
})

</script>

{#if isLoading}
    <div class="card small">
        <div class="spinner"></div> Loading configuration
    </div>
{:else}
    <div class="card small">
        <h3 class="section">Achievements Tracker</h3>
        <div class="section titleinfo row">
            <div class="col-sm-4" >
                <img src={titleInfo.logoUri} alt={`${titleInfo.productTitle} Logo`} />
            </div>
            <div class="col-sm-8">
                <button class="large primary" on:click={onForceRefresh} disabled={isRefreshing}>Force refresh</button>
            </div>
        </div>
        
        {#if xApiRateLimits != null}
        <div class="section">
            <h4>xApi.us calls</h4>
            <div class="row">
                <div class="col-sm-6">
                    Remaining
                </div>
                <div class="col-sm-6">
                    {xApiRateLimits.remaining}/{xApiRateLimits.hourlyLimit}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    Resets in
                </div>
                <div class="col-sm-6">
                    <CountDown targetDate={xApiRateLimits.resetTime} />
                </div>
            </div>
        </div>,
        <div class="section">
            Force refresh typically uses 1 call.<br/>
            15 auto-refresh per hour.
        </div>
        {/if}
    </div>
{/if}
