// TwitchAchievementTrackerFrontend/src/components/ConfigSteam_05_Confirm/ConfigSteam_05_Confirm.tsx
import * as React from 'react';
import * as Base from '../../common/ConfigStepBase';
import { ExtensionConfiguration, ActiveConfig } from '../../common/EBSTypes';
import { EBSVersion } from '../../common/ServerConfig';
import { ConfigurationService, ValidationError } from '../../services/EBSConfigurationService';
import ValidationErrorList from '../ValidationErrorList/ValidationErrorList';

interface ConfigSteam_05_ConfirmProps extends Base.ConfigStepBaseProps {
    webApiKey: string,
    steamProfileId: string,
    steamAppId: string,
    locale: string,
}

interface ConfigSteam_05_ConfirmState extends Base.ConfigStepBaseState {
    isLoading: boolean,
    errors: ValidationError[]
}

export default class ConfigSteam_05_Confirm extends Base.ConfigStepBase<ConfigSteam_05_ConfirmProps, ConfigSteam_05_ConfirmState> {
    state: ConfigSteam_05_ConfirmState = {
        isLoading: true,
        errors: [],
        isValid: false,
    }

    constructor(props: ConfigSteam_05_ConfirmProps){
        super(props);
    }

    componentDidMount = async () => {
            
        const configuration: ExtensionConfiguration = {
            activeConfig: ActiveConfig.Steam,
            steamConfig: {
                steamId: this.props.steamProfileId,
                webApiKey: this.props.webApiKey,
                appId: this.props.steamAppId,
                locale: this.props.locale
            },
            version: EBSVersion,
            xBoxLiveConfig: null
        }

        let errors = await ConfigurationService.validateConfiguration(configuration);
        errors = errors.filter(e => e.path == "SteamConfig.WebApiKey" || e.path == "SteamConfig.SteamId");

        this.setState({
            isLoading: false,
            errors: errors,
            isValid: errors.length == 0
        });
    }

    onSave = (_e: React.SyntheticEvent<HTMLInputElement>) => {
        let configuration: ExtensionConfiguration = {
            activeConfig: ActiveConfig.Steam,
            version: EBSVersion,
            xBoxLiveConfig: this.props.savedConfiguration?.xBoxLiveConfig, // Make sure we keep the non-active config saved
            steamConfig: {
                webApiKey: this.props.webApiKey,
                steamId: this.props.steamProfileId,
                appId: this.props.steamAppId,
                locale: this.props.locale,
            }
        };
        this.props.onValidate(this, configuration);
    }

    render(){
        let selection;
        let isSaveDisabled = this.state.isLoading || this.state.errors.length > 0;

        if (this.state.isLoading)
        {
            selection = (
                <div className="card">
                    <div className="spinner"></div>
                </div>
            )
        }
        else
        {
            selection = (
                <div className="card">
                    <div className="section">
                        ActiveConfig: Steam
                    </div>
                    <div className="section">
                        WebApiKey: {this.props.webApiKey}
                    </div>
                    <div className="section">
                        StreamerSteamId: {this.props.steamProfileId}
                    </div>
                    <div className="section">
                        AppId: {this.props.steamAppId}
                    </div>
                    <div className="section">
                        WebApiKey: {this.props.locale}
                    </div>
                </div>
            )
        }
        return [
            selection,
            <ValidationErrorList errors={this.state.errors} />,
            <input type="button" value="Back" onClick={this.onBack} />,
            <input type="button" value="Save" onClick={this.onSave} disabled={isSaveDisabled} />
        ]
    }
}

// TwitchAchievementTrackerFrontend/src/components/ConfigSteam_05_Confirm/ConfigSteam_05_Confirm.svelte
<script lang="ts">
import { EBSVersion } from "../../common/ServerConfig";
import { ActiveConfig, ExtensionConfiguration } from "../../common/EBSTypes";
import { ConfigurationService, ValidationError } from "../../services/EBSConfigurationService";
import ValidationErrorList from "../ValidationErrorList/ValidationErrorList.svelte";

export let onValidate: (e: any, configuration: ExtensionConfiguration) => void
export let onBack: (e: any) => void
export let savedConfiguration: ExtensionConfiguration
export let webApiKey: string 
export let steamProfileId: string
export let steamAppId: string
export let locale: string

let isLoading: boolean = true
let errors: ValidationError[] = []
let isValid: boolean = true


function onSave(e: any)
{
    let configuration: ExtensionConfiguration = {
        activeConfig: ActiveConfig.Steam,
        version: EBSVersion,
        xBoxLiveConfig: savedConfiguration?.xBoxLiveConfig, // Make sure we keep the non-active config saved
        steamConfig: {
            webApiKey: webApiKey,
            steamId: steamProfileId,
            appId: steamAppId,
            locale: locale,
        }
    };
    onValidate(e, configuration);
}

const configuration: ExtensionConfiguration = {
    activeConfig: ActiveConfig.Steam,
    steamConfig: {
        steamId: steamProfileId,
        webApiKey: webApiKey,
        appId: steamAppId,
        locale: locale
    },
    version: EBSVersion,
    xBoxLiveConfig: null
}

ConfigurationService.validateConfiguration(configuration)
    .then(newErrors => {
        errors = newErrors.filter(e => e.path == "SteamConfig.WebApiKey" || e.path == "SteamConfig.SteamId")
        isLoading = false
        isValid = errors.length == 0
    })

let isSaveDisabled: boolean
$: isSaveDisabled = isLoading || errors.length > 0
</script>

{#if isLoading}
<div class="card">
    <div class="spinner"></div>
</div>
{:else}
<div class="card">
    <div class="section">
        ActiveConfig: Steam
    </div>
    <div class="section">
        WebApiKey: {webApiKey}
    </div>
    <div class="section">
        StreamerSteamId: {steamProfileId}
    </div>
    <div class="section">
        AppId: {steamAppId}
    </div>
    <div class="section">
        WebApiKey: {locale}
    </div>
</div>
{/if}
<ValidationErrorList errors={errors} />
<input type="button" value="Back" on:click={onBack} />
<input type="button" value="Save" on:click={onSave} disabled={isSaveDisabled} />
