// TwitchAchievementTrackerFrontend/src/components/GamerCard/GamerCard.tsx
import * as React from "react";
import { PlayerInfoCard } from "../../common/EBSTypes";
import '../../../public/mini-default.min.css';

type GamerCardComponentProps = {
    playerInfo: PlayerInfoCard,
    buttonSection: React.ReactNode,
}

export default class GamerCardComponent extends React.Component<GamerCardComponentProps, any> {
    constructor(props: GamerCardComponentProps){
        super(props);
    }

    render(){
        return (
            <div className="card">
                <h2 className="section">{this.props.playerInfo.playerName}</h2>
                <div className="section">Id: {this.props.playerInfo.playerId}</div>
                <img src={this.props.playerInfo.avatarUrl} className="section media" />
                { this.props.buttonSection }
            </div>
        );
    }
}

// TwitchAchievementTrackerFrontend/src/components/GamerCard/GamerCard.svelte
<script lang="ts">
import type { PlayerInfoCard } from "../../common/EBSTypes";

export let playerInfo: PlayerInfoCard = null
</script>

<div class="card">
    <h2 class="section">{playerInfo.playerName}</h2>
    <div class="section">Id: {playerInfo.playerId}</div>
    <img src={playerInfo.avatarUrl} class="section media" alt="Avatar" />
    <slot name="buttonSection"></slot>
</div>
