// TwitchAchievementTrackerFrontend/src/components/AchievementsList/AchievementsList.tsx
import * as React from "react";
import { Achievement, ActiveConfig } from "../../common/EBSTypes";

interface AchievementsListProps {
    achievements: Achievement[],
    platform: ActiveConfig,
}

interface AchievementsListState {
}

export default class AchievementsList extends React.Component<AchievementsListProps, AchievementsListState> {
    constructor(props: AchievementsListProps){
        super(props);
    }

    render(){
        let platformClass = this.props.platform == ActiveConfig.XBoxLive ?  "steam" : "xboxlive";
        return (
            <ul id="list" className={platformClass}>
                {this.props.achievements.map((achievement, i)=> 
                    (
                        <li key={"achievement_" + i + "_" + achievement.id} className={achievement.completed ? "completed" : "notCompleted"}>
                            <div className="achievementTitle">
                                {achievement.name}
                            </div>
                            <div className="achievementDescription">
                                {achievement.description}
                            </div>
                        </li>
                    ))
                }
            </ul>
        )
    }
}

// TwitchAchievementTrackerFrontend/src/components/AchievementsList/AchievementsList.svelte
<script lang="ts">
    import { type Achievement, ActiveConfig } from "../../common/EBSTypes"

    export let achievements: Achievement[]
    export let platform: ActiveConfig

    let platformClass:string = ""
    $:{
        platformClass = platform == ActiveConfig.XBoxLive ?  "steam" : "xboxlive"
    }
</script>

<ul id="list" class={platformClass}>
    {#each achievements as achievement,i}
    {#key "achievement_" + i + "_" + achievement.id}
    <li class={achievement.completed ? "completed" : "notCompleted"}>
        <div class="achievementTitle">
            {achievement.name}
        </div>
        <div class="achievementDescription">
            {achievement.description}
        </div>
    </li>
    {/key}
    {/each}
</ul>
